// Code generated by tools/gensdktypes from sdkinit.go; DO NOT EDIT.
// SDK API contract shared by the runtime source and published editor types.
// Wire types are generated from the Go host; SDKInit embeds them in the same module.
import type {
  FileInfo,
  ImportInfo,
  FactsInfo,
  ViolationInput,
  DomainInfo,
} from "./types_gen";

export type Capability = "exact" | "structural" | "heuristic" | "advisory";

/** Published TermCases: renderings of a recorded vocabulary term as a
 * path or identifier segment. The same closed set rules.arclint.yaml accepts in
 * {name:<case>} placeholders. */
export type TermCase =
  | "flatcase"
  | "snake_case"
  | "kebab-case"
  | "camelCase"
  | "PascalCase";

export interface Ctx {
  /** Repository files, optionally filtered by a doublestar glob. */
  files(glob?: string): FileInfo[];
  /** Read one file's content. Throws on unreadable paths. */
  read(path: string): string;
  /** Classified imports of one file, for every active language target. */
  imports(path: string): ImportInfo[];
  /** Declared zone names to their member file paths. */
  zones(): Record<string, string[]>;
  /** Already-observed declarations, imports, and Zone memberships for one
   * selected subject, including incident dependencies; null outside Scope.
   * Check availability flags before treating empty arrays as observations. */
  facts(path: string): FactsInfo | null;
  /** The sorted zone names a file belongs to. */
  zoneOf(path: string): string[];
  /** The project's recorded domain model (domain.arclint.yaml);
   * empty collections when the project records none. Read-only:
   * declaring knowledge never creates a diagnostic by itself. */
  domain(): DomainInfo;
  /** Render a recorded term in one published TermCase, the host's
   * one casing implementation, identical to what rules.arclint.yaml
   * {name:<case>} placeholders resolve with. Throws on an unknown
   * case and on terms without letters or digits. */
  caseTerm(term: string, termCase: TermCase): string;
  /** Report one violation. */
  report(v: ViolationInput): void;
}

export interface Schema {
  optional(): Schema;
  default(v: unknown): Schema;
  describe(d: string): Schema;
  toJSON(): Record<string, unknown>;
}

/** Minimal zod-style schema builder producing JSON Schema; the host
 * validates rules.arclint.yaml params against it before check() runs. */
export declare const s: {
  string(): Schema;
  number(): Schema;
  integer(): Schema;
  boolean(): Schema;
  enum(...values: string[]): Schema;
  array(items: Schema): Schema;
  object(props: Record<string, Schema>): Schema;
};

export interface RuleDef {
  /** Unique rule type name, referenced by rules.arclint.yaml entries. */
  type: string;
  /** One-line summary shown by arclint rules. */
  description?: string;
  /** How this rule enforces its claim: exact (imports/syntax facts),
   * structural (paths/declarations), heuristic (names/regex/complexity),
   * advisory (guidance only). Default: heuristic, the conservative claim. */
  capability?: Capability;
  /** Params schema; YAML params are host-validated against it. */
  params?: Schema;
  check(ctx: Ctx, params: Record<string, unknown>): void;
}

export declare function defineRule(def: RuleDef): unknown;
