// Code generated by tygo. DO NOT EDIT.
// Code generated by tools/gensdktypes (tygo) from the sobek extension host types; DO NOT EDIT.

//////////
// source: types.go
/*
Package sobekextension implements the TypeScript extension SDK:
discovery under .arclint/extensions/, in-process transpilation via
esbuild, execution on sobek (the k6 pattern), a two-phase
register-then-run lifecycle, and a sandbox with no ambient I/O.

The types in this file are the host/extension wire contract. The
TypeScript declarations rule authors see are generated from these
structs (tools/gensdktypes, via tygo), so the .d.ts can never drift from
the host.
*/

/**
 * FileInfo is one repository file as exposed to ctx.files().
 */
export interface FileInfo {
  path: string;
  name: string;
  stem: string;
  ext: string;
  dir: string;
  size: number /* int */;
}
/**
 * ImportInfo is one classified import occurrence as exposed to
 * ctx.imports(path), for every active language target.
 */
export interface ImportInfo {
  path: string;
  line: number /* int */;
  /**
   * Class is stdlib | internal | external | unknown | cgo.
   */
  class: string;
  /**
   * TargetDir is the repo-relative package directory for internal
   * imports resolved into the tree, else "".
   */
  targetDir: string;
  /**
   * TargetFile is the repo-relative file an internal import resolves to
   * for file-granular languages (JS/TS, Python), else "".
   */
  targetFile: string;
}
/**
 * ParamInfo is one function or method parameter at the syntactic tier.
 */
export interface ParamInfo {
  /**
   * Name is the parameter identifier; "" for unnamed parameters.
   */
  name?: string;
  /**
   * Type is the source-text type annotation, never resolved.
   */
  type?: string;
  /**
   * Optional marks a marker or default the language expresses.
   */
  optional?: boolean;
  /**
   * Variadic marks rest or splat parameters.
   */
  variadic?: boolean;
}
/**
 * DeclInfo is one declaration as exposed through ctx.facts(path).
 */
export interface DeclInfo {
  /**
   * Kind is a small cross-language vocabulary: struct, interface,
   * type, class, enum, func, method, field, const, var.
   */
  kind: string;
  name: string;
  /**
   * Owner names the enclosing declaration for members (receiver
   * type, interface, class), else "".
   */
  owner: string;
  /**
   * Exported follows the language's own visibility convention.
   */
  exported: boolean;
  startLine: number /* int */;
  endLine: number /* int */;
  /**
   * Params and Results carry the syntactic signature of func and
   * method decls; absent for every other kind.
   */
  params?: ParamInfo[];
  results?: string[];
}
/**
 * FactsInfo is the cross-language declaration-fact view of one file as
 * exposed through ctx.facts(path). Languages return only declarations
 * they can support honestly.
 */
export interface FactsInfo {
  path: string;
  /**
   * Package is the Go package clause; "" for other languages.
   */
  package: string;
  decls: DeclInfo[];
  parseError?: string;
}
/**
 * ViolationInput is what ctx.report() accepts from a rule. Severity
 * is not part of the wire shape: in the target model it belongs to
 * the Rule, never to one finding.
 */
export interface ViolationInput {
  path: string;
  message: string;
  line?: number /* int */;
  fixHint?: string;
}
/**
 * DomainDefinitionInfo is one recorded project domain definition as
 * exposed through ctx.domain().
 */
export interface DomainDefinitionInfo {
  name: string;
  definition?: string;
  aliases?: string[];
  aggregate?: boolean;
}
/**
 * DomainInvariantInfo is one recorded invariant (statement + owner)
 * inside a bounded context as exposed through ctx.domain().
 */
export interface DomainInvariantInfo {
  statement: string;
  owner: string;
}
/**
 * DomainContextInfo is one bounded context and its recorded terms as
 * exposed through ctx.domain().
 */
export interface DomainContextInfo {
  name: string;
  entities: DomainDefinitionInfo[];
  valueObjects: DomainDefinitionInfo[];
  invariants: DomainInvariantInfo[];
  events: DomainDefinitionInfo[];
}
/**
 * DomainRelationInfo is one context-map edge as exposed through
 * ctx.domain().
 */
export interface DomainRelationInfo {
  from: string;
  to: string;
  kind: string;
}
/**
 * DomainInfo is the project's recorded domain model as exposed through
 * ctx.domain(): empty collections when the project records none.
 * Read-only: declaring knowledge never creates a diagnostic by itself.
 */
export interface DomainInfo {
  contexts: DomainContextInfo[];
  relations: DomainRelationInfo[];
}
