package sobekextension

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

//go:embed sdk/types_gen.ts
var sdkTypesTS string

// sdkAPIDecl is the hand-written half of arclint.d.ts: the SDK's API
// surface. The wire types (FileInfo, ImportInfo, ViolationInput) are
// generated from the Go host structs and injected alongside it.
const sdkAPIDecl = `
export type Capability = "exact" | "structural" | "heuristic" | "advisory";

export interface Ctx {
  /** Repository files, optionally filtered by a doublestar glob. */
  files(glob?: string): FileInfo[];
  /** Read one file's content. Throws on unreadable paths. */
  read(path: string): string;
  /** Classified imports of one file, for every active language target. */
  imports(path: string): ImportInfo[];
  /** Declared module names to their member file paths. */
  modules(): Record<string, string[]>;
  /** Declaration facts for one file; null when the file's language
   * does not supply declarations (today: Go only, parser-exact). */
  facts(path: string): FactsInfo | null;
  /** The sorted module names a file belongs to. */
  moduleOf(path: string): string[];
  /** Report one violation. */
  report(v: ViolationInput): void;
}

export interface Schema {
  optional(): Schema;
  default(v: unknown): Schema;
  describe(d: string): Schema;
  toJSON(): Record<string, unknown>;
}

/** Minimal zod-style schema builder producing JSON Schema; the host
 * validates rules.yaml params against it before check() runs. */
export const s: {
  string(): Schema;
  number(): Schema;
  integer(): Schema;
  boolean(): Schema;
  enum(...values: string[]): Schema;
  array(items: Schema): Schema;
  object(props: Record<string, Schema>): Schema;
};

export interface RuleDef {
  /** Unique rule type name, referenced by rules.yaml entries. */
  type: string;
  /** One-line summary shown by arclint rules. */
  description?: string;
  /** How this rule enforces its claim: exact (imports/syntax facts),
   * structural (paths/declarations), heuristic (names/regex/complexity),
   * advisory (guidance only). Default: heuristic, the conservative claim. */
  capability?: Capability;
  /** Params schema; YAML params are host-validated against it. */
  params?: Schema;
  check(ctx: Ctx, params: Record<string, unknown>): void;
}

export function defineRule(def: RuleDef): unknown;
`

const sdkTsconfig = `{
  "compilerOptions": {
    "target": "ES2017",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "noEmit": true,
    "paths": {
      "arclint": ["./arclint.d.ts"]
    }
  },
  "include": ["*.ts"]
}
`

// SDKInit writes .arclint/extensions/arclint.d.ts (assembled from the
// tygo-generated host types plus the SDK API declaration) and a
// tsconfig.json, giving authors full editor typing with no npm install.
// It returns the written paths.
func SDKInit(repoRoot string) ([]string, error) {
	dir := filepath.Join(repoRoot, filepath.FromSlash(ExtensionsDir))
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return nil, fmt.Errorf("create %s: %w", dir, err)
	}

	var b strings.Builder
	b.WriteString("// arclint extension SDK type declarations.\n")
	b.WriteString("// Generated by `arclint sdk init`; wire types derive from the Go host\n")
	b.WriteString("// structs (internal/ext/types.go) via tygo. Regenerate after upgrading.\n")
	b.WriteString("declare module \"arclint\" {\n")
	for _, block := range []string{sdkTypesTS, sdkAPIDecl} {
		for _, line := range strings.Split(block, "\n") {
			if strings.TrimSpace(line) == "" {
				b.WriteString("\n")
				continue
			}
			b.WriteString("  " + line + "\n")
		}
	}
	b.WriteString("}\n")

	dts := filepath.Join(dir, "arclint.d.ts")
	if err := os.WriteFile(dts, []byte(b.String()), 0o600); err != nil {
		return nil, fmt.Errorf("write %s: %w", dts, err)
	}
	tsconfig := filepath.Join(dir, "tsconfig.json")
	if err := os.WriteFile(tsconfig, []byte(sdkTsconfig), 0o600); err != nil {
		return nil, fmt.Errorf("write %s: %w", tsconfig, err)
	}
	return []string{dts, tsconfig}, nil
}

// Describe returns a one-line summary for `arclint rules ls`: the
// author's description when defineRule declares one, else a fallback.
func (rt *RuleType) Describe() string {
	if rt.Description != "" {
		return rt.Description
	}
	return fmt.Sprintf("extension rule type %q from %s", rt.Name, rt.SourcePath)
}
