// Code generated by tools/genmetamodel from metamodel.arclint.yaml; DO NOT EDIT.

package vocab

// ddd is the generated Domain-Driven Design meta-model; DDD returns it.
func ddd() MetaModel {
	return MetaModel{
		Name:        "ddd",
		Title:       "Domain-Driven Design",
		Description: "The vocabulary of Domain-Driven Design as arclint records and enforces it: strategic design names the models in play and the boundaries and relationships between them; tactical design names the building blocks a model is built from and the consistency rules each one carries.",
		Works: []Work{
			{
				Key:          "evans2015",
				Title:        "Domain-Driven Design Reference: Definitions and Pattern Summaries",
				Authors:      []string{"Eric Evans"},
				Year:         2015,
				URL:          "https://www.domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf",
				License:      "CC BY 4.0",
				Verification: VerifiedText,
			},
			{
				Key:          "evans2003",
				Title:        "Domain-Driven Design: Tackling Complexity in the Heart of Software",
				Authors:      []string{"Eric Evans"},
				Publisher:    "Addison-Wesley",
				Year:         2003,
				ISBN:         "978-0321125217",
				Verification: VerifiedCarried,
			},
			{
				Key:          "vernon2013",
				Title:        "Implementing Domain-Driven Design",
				Authors:      []string{"Vaughn Vernon"},
				Publisher:    "Addison-Wesley",
				Year:         2013,
				ISBN:         "978-0321834577",
				Verification: VerifiedCarried,
			},
			{
				Key:          "evans-fowler-1997",
				Title:        "Specifications",
				Authors:      []string{"Eric Evans", "Martin Fowler"},
				Year:         1997,
				URL:          "https://martinfowler.com/apsupp/spec.pdf",
				Verification: VerifiedText,
			},
			{
				Key:          "fowler-aggregate",
				Title:        "DDD_Aggregate",
				Authors:      []string{"Martin Fowler"},
				Date:         "2013-04-23",
				URL:          "https://martinfowler.com/bliki/DDD_Aggregate.html",
				Verification: VerifiedFetched,
			},
			{
				Key:          "fowler-bounded-context",
				Title:        "BoundedContext",
				Authors:      []string{"Martin Fowler"},
				Date:         "2014-01-15",
				URL:          "https://martinfowler.com/bliki/BoundedContext.html",
				Verification: VerifiedFetched,
			},
			{
				Key:          "fowler-ubiquitous-language",
				Title:        "UbiquitousLanguage",
				Authors:      []string{"Martin Fowler"},
				Date:         "2006-10-31",
				URL:          "https://martinfowler.com/bliki/UbiquitousLanguage.html",
				Verification: VerifiedFetched,
			},
			{
				Key:          "fowler-evans-classification",
				Title:        "EvansClassification",
				Authors:      []string{"Martin Fowler"},
				Date:         "2005-12-14",
				URL:          "https://martinfowler.com/bliki/EvansClassification.html",
				Verification: VerifiedFetched,
			},
			{
				Key:          "fowler-value-object",
				Title:        "ValueObject",
				Authors:      []string{"Martin Fowler"},
				Date:         "2016-11-14",
				URL:          "https://martinfowler.com/bliki/ValueObject.html",
				Verification: VerifiedFetched,
			},
			{
				Key:          "fowler-domain-event",
				Title:        "Domain Event",
				Authors:      []string{"Martin Fowler"},
				Date:         "2005-12-12",
				URL:          "https://martinfowler.com/eaaDev/DomainEvent.html",
				Verification: VerifiedFetched,
			},
			{
				Key:          "fowler-architecture",
				Title:        "Software Architecture Guide",
				Authors:      []string{"Martin Fowler"},
				Date:         "2019-08-01",
				URL:          "https://martinfowler.com/architecture/",
				Verification: VerifiedFetched,
			},
			{
				Key:          "fowler-anemic-domain-model",
				Title:        "AnemicDomainModel",
				Authors:      []string{"Martin Fowler"},
				Date:         "2003-11-25",
				URL:          "https://martinfowler.com/bliki/AnemicDomainModel.html",
				Verification: VerifiedFetched,
			},
		},
		Facts: []FactDefinition{
			{
				Name:       "file_tree",
				Definition: "The walked repository file list.",
				Languages:  Languages{All: true},
			},
			{
				Name:       "imports",
				Definition: "The classified per-file import view, each import resolved to stdlib, a declared Zone, a manifest dependency, or unknown.",
				Languages:  Languages{All: true},
			},
			{
				Name:       "declarations",
				Definition: "The per-file declaration view: kind, name, owner, exported, lines, and the syntactic signature of functions and methods. Go emits struct, interface, type, func, method, field, const, and var; TypeScript emits class, interface, type, enum, func, method, field, const, and var; Python emits class, method, and func only.",
				Languages:  Languages{All: true},
			},
			{
				Name:       "calls",
				Definition: "The per-file call view: callee identifier, line, and enclosing function, parser-exact and unresolved.",
				Languages:  Languages{All: true},
			},
		},
		Milestones: []Milestone{
			{
				Key:     "field-declarations",
				Needs:   "Field declarations from the Python adapter, which emits class, method, and func today.",
				Unlocks: []string{"value_object/no-identity", "domain_event/occurrence-time", "domain_service/stateless"},
			},
			{
				Key:     "field-types",
				Needs:   "The declared type of every field, so that a field of the recorded identity type can be told from any other, and a root held in a field from an identity held there.",
				Unlocks: []string{"entity/identity", "aggregate/root-only-references"},
			},
			{
				Key:     "field-mutability",
				Needs:   "Whether a field can be assigned after construction, in each language's own idiom.",
				Unlocks: []string{"value_object/immutable-fields", "domain_event/immutable"},
			},
			{
				Key:     "resolved-calls",
				Needs:   "The declaration a call resolves to, so that a call from an aggregate into a repository, or an equality check that compares identities, is a fact rather than a name match.",
				Unlocks: []string{"repository/not-called-from-aggregates", "entity/equality-by-identity"},
			},
			{
				Key:     "transaction-facts",
				Needs:   "The unit of work a repository save belongs to, which no syntactic fact carries.",
				Unlocks: []string{"aggregate/one-per-transaction"},
			},
		},
		Phases: []Phase{
			{
				Name:  "strategic",
				Title: "Strategic design",
				Definition: Meaning{
					Text: "The part of Domain-Driven Design that decides which models are in play, where each applies, and how they relate: bounded contexts, the ubiquitous language inside each, the context map between them, and the distillation that separates the core domain from the rest.",
					Sources: []Citation{
						{Work: "evans2015", Page: "28", Section: "Context Mapping for Strategic Design"},
						{Work: "evans2015", Page: "40", Section: "Core Domain"},
					},
				},
			},
			{
				Name:  "tactical",
				Title: "Tactical design",
				Definition: Meaning{
					Text: "The building blocks a single model is built from and the consistency rules each carries: entities, value objects, aggregates and their invariants, domain events, services, repositories, factories, modules, and the supple-design practices of assertions and specifications.",
					Sources: []Citation{
						{Work: "evans2015", Page: "9", Section: "Building Blocks of a Model-Driven Design"},
						{Work: "evans2015", Page: "19", Section: "Supple Design"},
					},
				},
			},
			{
				Name:  "structural",
				Title: "Structural vocabulary",
				Definition: Meaning{
					Text: "arclint's own terms for the physical layout of a codebase: what it observes and where its rules apply. They are defined here and not cited, because arclint is their source; they are not part of Domain-Driven Design and never appear in a project's domain file.",
				},
			},
		},
		Blocks: []BuildingBlock{
			{
				Term:  "domain",
				Title: "Domain",
				Phase: "strategic",
				Definition: Meaning{
					Text: "A sphere of knowledge, influence, or activity. The subject area to which the user applies a program is the domain of the software.",
					Sources: []Citation{
						{Work: "evans2015", Page: "vi", Section: "Definitions"},
					},
				},
				Records: Recording{
					Section: SectionTop,
					Note:    "A project's domain is the whole of its domain.arclint.yaml; the file names it once at the top.",
					Properties: []Property{
						{Name: "project", Required: true, Definition: "The name of the software whose domain the file records."},
						{Name: "description", Required: false, Definition: "The domain in a few sentences, as the people in it would tell a newcomer."},
						{Name: "contexts", Required: true, Definition: "The bounded contexts in play, a map keyed by context name; one model each."},
						{Name: "relations", Required: false, Definition: "The context map: the relations between the recorded contexts, each upstream first."},
					},
				},
			},
			{
				Term:  "model",
				Title: "Model",
				Phase: "strategic",
				Definition: Meaning{
					Text: "A system of abstractions that describes selected aspects of a domain and can be used to solve problems related to that domain. A model has meaning only inside a bounded context.",
					Sources: []Citation{
						{Work: "evans2015", Page: "vi", Section: "Definitions"},
						{Work: "evans2015", Page: "2", Section: "Bounded Context"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "One model per bounded context; the context's recorded terms are the model.",
				},
			},
			{
				Term:  "ubiquitous_language",
				Title: "Ubiquitous Language",
				Phase: "strategic",
				Definition: Meaning{
					Text: "A language structured around the domain model and used by all team members within a bounded context to connect all the activities of the team with the software. The model is the backbone of the language; the code uses the same terms as the conversation, and a change in the language is a change to the model.",
					Sources: []Citation{
						{Work: "evans2015", Page: "vi", Section: "Definitions"},
						{Work: "evans2015", Page: "4", Section: "Ubiquitous Language"},
						{Work: "fowler-ubiquitous-language"},
						{Work: "evans2003", Chapter: 2, Page: "24"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "A project's Ubiquitous Language is the whole of domain.arclint.yaml, one file per repository, one section per bounded context.",
				},
				Invariants: []BlockInvariant{
					{
						ID:        "ubiquitous_language/terms-carry-definitions",
						Statement: "Every recorded term carries a non-empty definition; an identity an aggregate or entity names is the one term recorded without an entry of its own.",
						Sources: []Citation{
							{Work: "evans2015", Page: "4", Section: "Ubiquitous Language"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "ubiquitous_language/one-meaning-per-name",
						Statement: "A name is recorded once within a bounded context, whatever the section; the same name recorded as an aggregate and again as a value object, or as an identity and again as an event, is rejected, because one context has one model. A name recorded twice in one section is rejected by the parser before the loader sees it.",
						Sources: []Citation{
							{Work: "evans2015", Page: "2", Section: "Bounded Context"},
							{Work: "evans2015", Page: "vi", Section: "Definitions"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "ubiquitous_language/terms-declared-in-code",
						Statement: "Every recorded member entity, value object, and identity names one type declaration in the context's code, spelled with the recorded name in the language's type case (in Go, a name the package's own name completes, so rule.ID spells RuleID); a name no declaration spells, or one that two declarations spell with nothing to choose between them, is a finding. Aggregates, events, services, specifications, repositories, and factories state the same for themselves.",
						Sources: []Citation{
							{Work: "evans2015", Page: "4", Section: "Ubiquitous Language"},
							{Work: "evans2015", Page: "20", Section: "Intention-Revealing Interfaces"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Name classes and operations to describe their effect and purpose, without reference to the means by which they do what they promise, and make those names conform to the ubiquitous language.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "20", Section: "Intention-Revealing Interfaces"},
						},
					},
					{
						Text: "Identifiers in the model carry no technical jargon; a term the domain expert would not say is a translation, and translation blunts communication.",
						Sources: []Citation{
							{Work: "evans2015", Page: "3", Section: "Ubiquitous Language"},
							{Work: "vernon2013", Chapter: 2, Page: "53"},
						},
					},
				},
			},
			{
				Term:  "context",
				Title: "Context",
				Phase: "strategic",
				Definition: Meaning{
					Text: "The setting in which a word or statement appears that determines its meaning. Statements about a model can only be understood in a context.",
					Sources: []Citation{
						{Work: "evans2015", Page: "vi", Section: "Definitions"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "The general notion; a project records bounded contexts.",
				},
			},
			{
				Term:  "bounded_context",
				Title: "Bounded Context",
				Phase: "strategic",
				Definition: Meaning{
					Text: "A description of a boundary, typically a subsystem or the work of a particular team, within which a particular model is defined and applicable. The boundary is set explicitly in terms of team organization, usage within specific parts of the application, and physical manifestations such as code bases and database schemas.",
					Sources: []Citation{
						{Work: "evans2015", Page: "vi", Section: "Definitions"},
						{Work: "evans2015", Page: "2", Section: "Bounded Context"},
						{Work: "fowler-bounded-context"},
						{Work: "vernon2013", Chapter: 2, Page: "62"},
					},
				},
				Records: Recording{
					Section: SectionContexts,
					Note:    "A map keyed by context name; the key is the name. The context's code is located from its recorded terms: the declarations that spell them, found in the repository, and the code is the packages or files holding its aggregate roots plus the file of every other term. When rules.arclint.yaml declares a Zone spelled with the context's name, the terms are looked for in that Zone alone and every file of the Zone is the context's code.",
					Properties: []Property{
						{Name: "name", Required: true, Definition: "The context's name, lowercase, part of the ubiquitous language; the map key."},
						{Name: "definition", Required: true, Definition: "What the context is responsible for and which model it holds."},
						{Name: "aggregates", Required: false, Definition: "The context's aggregates, each with its identity, member entities, invariants, assertions, repository, and factory."},
						{Name: "value_objects", Required: false, Definition: "Value objects of the context, each with its invariants."},
						{Name: "events", Required: false, Definition: "The context's domain events."},
						{Name: "services", Required: false, Definition: "The context's domain services."},
						{Name: "specifications", Required: false, Definition: "The context's specifications."},
						{Name: "questions", Required: false, Definition: "Open questions about the model, keyed, recorded in place of a guess; a question is never a rule and nothing is enforced from it."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "bounded_context/named-once",
						Statement: "A bounded context has a non-empty name, and no two contexts share one.",
						Sources: []Citation{
							{Work: "evans2015", Page: "29", Section: "Context Map"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "bounded_context/code-held-by-one-context",
						Statement: "A file of a bounded context's code belongs to no other context; two contexts hold the same code only under a recorded shared_kernel relation between them, because a boundary two models straddle is not a boundary.",
						Sources: []Citation{
							{Work: "evans2015", Page: "2", Section: "Bounded Context"},
							{Work: "evans2015", Page: "31", Section: "Shared Kernel"},
							{Work: "evans2003", Chapter: 14, Page: "335"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "bounded_context/isolated",
						Statement: "Code of one bounded context imports code of another only along a recorded relation between the two; an import between contexts the context map does not relate is a finding.",
						Sources: []Citation{
							{Work: "evans2015", Page: "2", Section: "Bounded Context"},
							{Work: "evans2015", Page: "28", Section: "upstream-downstream"},
							{Work: "evans2003", Chapter: 14, Page: "335"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations", "imports"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Keep model concepts and terms strictly consistent within the bounds, and standardize a single development process within the context, which need not be used elsewhere.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "2", Section: "Bounded Context"},
						},
					},
					{
						Text: "Two contexts do not share a database schema or a memory space; sharing either dissolves the boundary.",
						Sources: []Citation{
							{Work: "vernon2013", Chapter: 2, Page: "68"},
						},
					},
				},
			},
			{
				Term:  "context_map",
				Title: "Context Map",
				Phase: "strategic",
				Definition: Meaning{
					Text: "The named bounded contexts in play on a project and the points of contact between their models: the translation for any communication, what is shared, what is isolated, and which way influence runs. It maps the existing terrain; transformations come later.",
					Sources: []Citation{
						{Work: "evans2015", Page: "29", Section: "Context Map"},
						{Work: "fowler-bounded-context"},
						{Work: "vernon2013", Chapter: 3, Page: "87"},
					},
				},
				Records: Recording{
					Section: SectionRelations,
					Note:    "The context map is the set of recorded relations; it has no entry of its own.",
				},
				Invariants: []BlockInvariant{
					{
						ID:        "context_map/relations-name-recorded-contexts",
						Statement: "A relation names two recorded bounded contexts, upstream first, and the same relation is not recorded twice.",
						Sources: []Citation{
							{Work: "evans2015", Page: "29", Section: "Context Map"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "context_map/one-relation-per-pair",
						Statement: "A relation joins two distinct contexts, and one pair of contexts carries at most one relation; a context related to itself, or a pair recorded under two kinds, is rejected.",
						Sources: []Citation{
							{Work: "evans2015", Page: "29", Section: "Context Map"},
							{Work: "evans2015", Page: "28", Section: "upstream-downstream"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Identify each model in play on the project, including the implicit models of non-object-oriented subsystems, and give each bounded context a name that is part of the ubiquitous language.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "29", Section: "Context Map"},
						},
					},
				},
			},
			{
				Term:  "context_relation",
				Title: "Context Relation",
				Phase: "strategic",
				Definition: Meaning{
					Text: "One point of contact on the context map, a relationship between an upstream context, whose actions affect the downstream context's success, and a downstream context, whose actions do not significantly affect the upstream. Its kind is one of the published relationship patterns.",
					Sources: []Citation{
						{Work: "evans2015", Page: "28", Section: "upstream-downstream"},
						{Work: "evans2015", Page: "29", Section: "Context Map"},
					},
				},
				Records: Recording{
					Section: SectionRelations,
					Properties: []Property{
						{Name: "from", Required: true, Definition: "The upstream context."},
						{Name: "to", Required: true, Definition: "The downstream context."},
						{Name: "kind", Required: true, Definition: "One of the published kinds below."},
						{Name: "description", Required: false, Definition: "What passes between the two contexts and which way, in the ubiquitous language."},
					},
					Kinds: []KindDefinition{
						{
							Name:       "partnership",
							Definition: "The two contexts succeed or fail together; the teams coordinate planning and the evolution of their interfaces. Influence runs both ways.",
							Sources: []Citation{
								{Work: "evans2015", Page: "30", Section: "Partnership"},
							},
						},
						{
							Name:       "shared_kernel",
							Definition: "An explicitly bounded subset of the model, and the code and database design associated with it, that the two teams agree to share and change only in consultation. Influence runs both ways.",
							Sources: []Citation{
								{Work: "evans2015", Page: "31", Section: "Shared Kernel"},
							},
						},
						{
							Name:       "customer_supplier",
							Definition: "The downstream team is the upstream team's customer; downstream priorities factor into upstream planning and jointly developed acceptance tests validate the interface.",
							Sources: []Citation{
								{Work: "evans2015", Page: "32", Section: "Customer/Supplier Development"},
							},
						},
						{
							Name:       "conformist",
							Definition: "The downstream team eliminates translation by adhering to the upstream model as it is, sharing the upstream's ubiquitous language.",
							Sources: []Citation{
								{Work: "evans2015", Page: "33", Section: "Conformist"},
							},
						},
						{
							Name:       "anticorruption_layer",
							Definition: "The downstream context isolates itself with a layer that presents the upstream's functionality in terms of the downstream's own model, translating in one or both directions.",
							Sources: []Citation{
								{Work: "evans2015", Page: "34", Section: "Anticorruption Layer"},
							},
						},
						{
							Name:       "open_host_service",
							Definition: "The upstream context defines an open protocol giving access to its subsystem as a set of services, augmented by one-off translators only for idiosyncratic clients.",
							Sources: []Citation{
								{Work: "evans2015", Page: "35", Section: "Open-host Service"},
							},
						},
						{
							Name:       "published_language",
							Definition: "The two contexts translate through a well-documented shared language that can express the necessary domain information, often combined with an open-host service.",
							Sources: []Citation{
								{Work: "evans2015", Page: "36", Section: "Published Language"},
							},
						},
						{
							Name:       "separate_ways",
							Definition: "The two contexts have no connection at all, so each may find simple, specialized solutions within its own scope.",
							Sources: []Citation{
								{Work: "evans2015", Page: "37", Section: "Separate Ways"},
							},
						},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "context_relation/published-kind",
						Statement: "A relation's kind is one of the published kinds; any other spelling is rejected.",
						Sources: []Citation{
							{Work: "evans2015", Page: "29", Section: "Context Map"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "context_relation/imports-follow-influence",
						Statement: "Under a one-way kind (customer_supplier, conformist, anticorruption_layer, open_host_service, published_language) only the downstream context's code imports the upstream's; under partnership or shared_kernel both may import each other; under separate_ways neither imports the other.",
						Sources: []Citation{
							{Work: "evans2015", Page: "28", Section: "upstream-downstream"},
							{Work: "evans2015", Page: "37", Section: "Separate Ways"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations", "imports"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
			},
			{
				Term:  "core_domain",
				Title: "Core Domain",
				Phase: "strategic",
				Definition: Meaning{
					Text: "The critical core of the model, the real business asset, boiled down and kept small so it can be distinguished from the mass of supporting model and code, and where the deepest model and the best developers are invested.",
					Sources: []Citation{
						{Work: "evans2015", Page: "40", Section: "Core Domain"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "A designation of a context, not a recorded entry; the ruleset's Zones and Rules carry the investment it asks for.",
				},
				Guidance: []Guidance{
					{
						Text:        "Justify investment in any other part of the system by how it supports the distilled core.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "40", Section: "Core Domain"},
						},
					},
				},
			},
			{
				Term:  "generic_subdomain",
				Title: "Generic Subdomain",
				Phase: "strategic",
				Definition: Meaning{
					Text: "A cohesive subdomain that is not the motivation for the project, factored out into a separate module as a generic model, kept free of the project's specialties, and developed with lower priority than the core domain.",
					Sources: []Citation{
						{Work: "evans2015", Page: "41", Section: "Generic Subdomains"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "A designation of a context or Zone, not a recorded entry.",
				},
				Guidance: []Guidance{
					{
						Text:        "Consider off-the-shelf solutions or published models for a generic subdomain, and avoid assigning core developers to it.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "41", Section: "Generic Subdomains"},
						},
					},
				},
			},
			{
				Term:  "big_ball_of_mud",
				Title: "Big Ball of Mud",
				Phase: "strategic",
				Definition: Meaning{
					Text: "A part of a system where models are mixed and boundaries are inconsistent, designated as such by drawing a boundary around the whole mess so that no sophisticated modeling is attempted inside it and it is kept from sprawling into other contexts.",
					Sources: []Citation{
						{Work: "evans2015", Page: "38", Section: "Big Ball of Mud"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "A designation of a context; in a ruleset it is a Zone other Zones may not import from.",
				},
			},
			{
				Term:  "domain_isolation",
				Title: "Isolating the Domain",
				Phase: "tactical",
				Definition: Meaning{
					Text: "The expression of the domain model and the business logic kept free of any dependency on infrastructure, user interface, or application logic that is not business logic, so that the domain objects, relieved of displaying, storing, and managing themselves, can be focused on expressing the model. The key goal is isolation; a layered architecture is one way to reach it, and hexagonal and related patterns serve as well or better to the degree that they keep the model's expression free of references to other system concerns. Domain-Driven Design demands the isolation, not any one architecture around it.",
					Sources: []Citation{
						{Work: "evans2015", Page: "10", Section: "Layered Architecture"},
						{Work: "evans2003", Chapter: 4, Section: "Isolating the Domain"},
						{Work: "fowler-architecture"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "The architecture, whichever one, is the Zones of rules.arclint.yaml and the Rules between them; the domain file does not repeat it, and the isolation can only be judged where the ruleset declares Zones. The only demand the meta-model makes of the architecture is the isolation below.",
				},
				Invariants: []BlockInvariant{
					{
						ID:        "domain_isolation/model-imports-nothing-outside-itself",
						Statement: "Code of a bounded context imports no code of a declared Zone that no context holds; whatever the architecture, dependencies run toward the model and never out of it. Without a declared Zone there is no outside to judge, and the invariant does not apply.",
						Sources: []Citation{
							{Work: "evans2015", Page: "10", Section: "Layered Architecture"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations", "imports"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Concentrate all the code related to the domain model in one place and isolate it from the user interface, application, and infrastructure code.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "10", Section: "Layered Architecture"},
						},
					},
				},
			},
			{
				Term:  "entity",
				Title: "Entity",
				Phase: "tactical",
				Definition: Meaning{
					Text: "An object defined primarily by its identity rather than its attributes: a thread of identity that runs through time and often across distinct representations, whose attributes may change while it stays the same thing. The model defines what it means to be the same thing.",
					Sources: []Citation{
						{Work: "evans2015", Page: "11", Section: "Entities"},
						{Work: "fowler-evans-classification"},
						{Work: "vernon2013", Chapter: 5, Page: "171"},
					},
				},
				Records: Recording{
					Section: SectionEntities,
					Note:    "Every entity is either the root of an aggregate, recorded as the aggregate itself, or a member of one, recorded under that aggregate's entities; there is no entity outside an aggregate. A member's identity is local, distinct only inside its aggregate.",
					Properties: []Property{
						{Name: "name", Required: true, Definition: "The entity's name in the ubiquitous language, the name of its type in the code; the map key."},
						{Name: "definition", Required: true, Definition: "What the entity is and what identity means for it."},
						{Name: "identity", Required: false, Definition: "The value object that is the member's local identity, when the member has one worth naming."},
						{Name: "aliases", Required: false, Definition: "Other names the team uses for the same term."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "entity/identity",
						Statement: "An entity declares a field whose type is its recorded identity, distinguishing it from every other object of its kind regardless of attributes.",
						Sources: []Citation{
							{Work: "evans2015", Page: "11", Section: "Entities"},
							{Work: "vernon2013", Chapter: 5, Page: "173"},
						},
						Enforcement: Enforcement{
							Facts:    []string{"declarations"},
							Needs:    "field-types",
							Severity: severityError,
						},
					},
					{
						ID:        "entity/equality-by-identity",
						Statement: "Two entities are the same when their identities are the same, whatever their attributes.",
						Sources: []Citation{
							{Work: "evans2015", Page: "11", Section: "Entities"},
							{Work: "vernon2013", Chapter: 5, Page: "174"},
						},
						Enforcement: Enforcement{
							Facts:    []string{"declarations", "calls"},
							Needs:    "resolved-calls",
							Severity: severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "When an object is distinguished by its identity rather than its attributes, make this primary to its definition in the model; keep the class definition simple and focused on life cycle continuity and identity.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "11", Section: "Entities"},
						},
					},
					{
						Text: "Move descriptive attributes and their logic into value objects, so the entity is left with identity and life cycle.",
						Sources: []Citation{
							{Work: "evans2015", Page: "11", Section: "Entities"},
							{Work: "vernon2013", Chapter: 10, Page: "382"},
						},
					},
					{
						Text: "An entity inside an aggregate has a local identity that needs to be distinguishable only within the aggregate; only the root carries a global one.",
						Sources: []Citation{
							{Work: "evans2003", Chapter: 6, Page: "127"},
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
						},
					},
				},
			},
			{
				Term:  "value_object",
				Title: "Value Object",
				Phase: "tactical",
				Definition: Meaning{
					Text: "An object that describes or computes some characteristic of a thing and has no conceptual identity: it matters only as the combination of its attributes, two with the same attribute values are equal, and it is treated as immutable, with every operation a side-effect-free function.",
					Sources: []Citation{
						{Work: "evans2015", Page: "12", Section: "Value Objects"},
						{Work: "fowler-value-object"},
						{Work: "fowler-evans-classification"},
						{Work: "vernon2013", Chapter: 6, Page: "219"},
					},
				},
				Records: Recording{
					Section: SectionValueObjects,
					Note:    "A map keyed by name. An identity named by an aggregate or a member entity is a value object of the context whether or not it is recorded here; record it only when there is more to say than that it identifies its entity.",
					Properties: []Property{
						{Name: "name", Required: true, Definition: "The value object's name, the name of its type in the code; the map key."},
						{Name: "definition", Required: true, Definition: "What the value describes and what makes two of them equal."},
						{Name: "aliases", Required: false, Definition: "Other names the team uses for the same term."},
						{Name: "invariants", Required: false, Definition: "The conditions a value of this kind always satisfies, a map from key to statement; a value that would violate one is never constructed."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "value_object/constructed-through-one-door",
						Statement: "A value object with a recorded invariant declares a constructor: a function of its module that returns it, or a constructor or __init__ of its class, or a factory method on it named create, from, of, parse, new, or build; the invariant is enforced there, so a value that violates it never exists.",
						Sources: []Citation{
							{Work: "evans2015", Page: "12", Section: "Value Objects"},
							{Work: "evans2015", Page: "18", Section: "Factories"},
							{Work: "vernon2013", Chapter: 6, Page: "221"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "value_object/no-setters",
						Statement: "A value object declares no method whose name begins with set; nothing changes a value after construction.",
						Sources: []Citation{
							{Work: "evans2015", Page: "12", Section: "Value Objects"},
							{Work: "fowler-value-object"},
							{Work: "vernon2013", Chapter: 6, Page: "221"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "value_object/no-identity",
						Statement: "A value object declares no identity field; identity is what makes an entity, and a value object has none.",
						Sources: []Citation{
							{Work: "evans2015", Page: "12", Section: "Value Objects"},
							{Work: "vernon2013", Chapter: 6, Page: "221"},
						},
						Enforcement: Enforcement{
							Facts:     []string{"declarations"},
							Languages: Languages{Names: []string{"go", "typescript"}},
							Needs:     "field-declarations",
							Severity:  severityError,
						},
					},
					{
						ID:        "value_object/immutable-fields",
						Statement: "Every field of a value object is immutable after construction.",
						Sources: []Citation{
							{Work: "evans2015", Page: "12", Section: "Value Objects"},
							{Work: "fowler-value-object"},
							{Work: "vernon2013", Chapter: 6, Page: "221"},
						},
						Enforcement: Enforcement{
							Facts:    []string{"declarations"},
							Needs:    "field-mutability",
							Severity: severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Make all operations of a value object side-effect-free functions that do not depend on any mutable state, and move complex logic into value objects when a concept fitting the responsibility presents itself.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "21", Section: "Side-Effect-Free Functions"},
							{Work: "vernon2013", Chapter: 6, Page: "228"},
						},
					},
				},
			},
			{
				Term:  "invariant",
				Title: "Invariant",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A consistency rule that must hold whenever the objects it constrains can be observed: an aggregate's invariants hold at the end of every operation on the aggregate, and a value object's invariants hold for every value that exists. The aggregate root, or the value object's constructor, is responsible for enforcing it, so that a state violating it is never reachable. In the code an invariant is stated as an assertion.",
					Sources: []Citation{
						{Work: "evans2015", Page: "16", Section: "Aggregates"},
						{Work: "evans2015", Page: "22", Section: "Assertions"},
						{Work: "vernon2013", Chapter: 10, Page: "353"},
					},
				},
				Records: Recording{
					Section: SectionInvariants,
					Note:    "A map from key to statement, recorded under the aggregate or value object that owns it; the owner is the nesting, never a reference.",
					Properties: []Property{
						{Name: "key", Required: true, Definition: "The rule's name in kebab-case, unique within its owner and stable across edits: it is how a finding, a suppression, and a baseline refer to the rule. For an aggregate's invariant it also names the root method that enforces it: ensure followed by the key, spelled in the language's method case, so lines-frozen is enforced by EnsureLinesFrozen in Go, ensureLinesFrozen in TypeScript, and ensure_lines_frozen in Python."},
						{Name: "statement", Required: true, Definition: "The rule in the ubiquitous language, as a domain expert would state it."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "invariant/owned-by-aggregate-or-value-object",
						Statement: "An invariant is owned by exactly one recorded aggregate or value object; an invariant written under a member entity, an event, or under nothing, is rejected.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "evans2015", Page: "22", Section: "Assertions"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "invariant/keyed-within-owner",
						Statement: "Every invariant carries a kebab-case key, unique within its owner and distinct from the owner's assertion keys; the parser rejects a key recorded twice under one owner, and the loader rejects an empty key or an empty statement.",
						Sources: []Citation{
							{Work: "evans2015", Page: "22", Section: "Assertions"},
							{Work: "vernon2013", Chapter: 10, Page: "353"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "invariant/key-names-the-rule",
						Statement: "An invariant's key names the rule it protects, in the ubiquitous language; a key that names only the act of checking (validate, check, verify, is-valid, check-rules, ensure, assert, guard) is rejected, because a name that describes the means says nothing about the effect.",
						Sources: []Citation{
							{Work: "evans2015", Page: "20", Section: "Intention-Revealing Interfaces"},
							{Work: "evans2015", Page: "4", Section: "Ubiquitous Language"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "invariant/enforced-at-every-mutation",
						Statement: "Every constructor and every command of the root calls the ensure method of the aggregate's invariant, so the invariant is evaluated at the completion of every state-mutating operation and a violation fails the operation; a root with no constructor has no door at which to enforce it.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "vernon2013", Chapter: 10, Page: "354"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations", "calls"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Model true invariants in consistency boundaries; a rule that can tolerate a delay is not an invariant of the aggregate and belongs to eventual consistency outside it.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "vernon2013", Chapter: 10, Page: "353"},
						},
					},
					{
						Text: "Report a refused operation under the name of the rule that refused it, so that the interface tells which rule failed without a trace through the implementation.",
						Sources: []Citation{
							{Work: "evans2015", Page: "20", Section: "Intention-Revealing Interfaces"},
						},
					},
					{
						Text: "Keep the rule's logic on the aggregate or value object that owns it; a model whose objects are bags of getters and setters, with the rules pushed out to services, is anemic and has none of the benefits of a domain model.",
						Sources: []Citation{
							{Work: "fowler-anemic-domain-model"},
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
						},
					},
				},
			},
			{
				Term:  "assertion",
				Title: "Assertion",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A stated post-condition of an operation or invariant of a class or aggregate, made explicit so that the effect of an operation can be known without tracing its implementation. Assertions define the contracts of services and entity modifiers and the invariants on aggregates; where they cannot be coded directly, they are written as automated unit tests.",
					Sources: []Citation{
						{Work: "evans2015", Page: "22", Section: "Assertions"},
						{Work: "evans2003", Chapter: 10, Page: "255"},
						{Work: "vernon2013", Chapter: 5, Page: "208"},
					},
				},
				Records: Recording{
					Section: SectionAssertions,
					Note:    "A map keyed by the assertion's name, recorded under the aggregate whose operation it constrains.",
					Properties: []Property{
						{Name: "key", Required: true, Definition: "The assertion's name in kebab-case, unique within its owner; the root's method that checks it is assert followed by the key, spelled in the language's method case (AssertHasLines, assertHasLines, assert_has_lines)."},
						{Name: "on", Required: true, Definition: "The operation of the root whose completion the assertion constrains."},
						{Name: "statement", Required: true, Definition: "The post-condition in the ubiquitous language."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "assertion/names-owner-operation-and-check",
						Statement: "An assertion carries a statement, names the operation it constrains, and carries a key naming the method that checks it.",
						Sources: []Citation{
							{Work: "evans2015", Page: "22", Section: "Assertions"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "assertion/owned-by-an-aggregate",
						Statement: "An assertion is recorded under one aggregate; an assertion under a value object, a member entity, or nothing is rejected.",
						Sources: []Citation{
							{Work: "evans2015", Page: "22", Section: "Assertions"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "assertion/checked-by-its-operation",
						Statement: "The root declares both the operation and the checking method (assert followed by the key in the language's method case), and the operation calls the checking method.",
						Sources: []Citation{
							{Work: "evans2015", Page: "22", Section: "Assertions"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations", "calls"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "State post-conditions of operations and invariants of classes and aggregates explicitly; where they cannot be coded directly, write automated unit tests for them.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "22", Section: "Assertions"},
						},
					},
					{
						Text: "Seek models with coherent sets of concepts that lead a developer to infer the intended assertions.",
						Sources: []Citation{
							{Work: "evans2015", Page: "22", Section: "Assertions"},
							{Work: "evans2003", Chapter: 10, Page: "256"},
						},
					},
				},
			},
			{
				Term:  "specification",
				Title: "Specification",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A predicate-like value object that tells whether a candidate object matches some criteria, separating the statement of what kind of objects can be selected from the object that does the selecting. It answers through one operation, isSatisfiedBy, and can be combined with other specifications.",
					Sources: []Citation{
						{Work: "evans-fowler-1997", Page: "2"},
						{Work: "evans2015", Page: "25", Section: "Declarative Design"},
					},
				},
				Records: Recording{
					Section: SectionSpecifications,
					Properties: []Property{
						{Name: "name", Required: true, Definition: "The specification's name, the name of its type in the code; the map key."},
						{Name: "definition", Required: true, Definition: "The criteria it states, in the ubiquitous language."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "specification/satisfaction-method",
						Statement: "A specification is a declared type carrying a satisfaction method (SatisfiedBy, satisfiedBy, or satisfied_by).",
						Sources: []Citation{
							{Work: "evans-fowler-1997", Page: "2"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
			},
			{
				Term:  "business_rule",
				Title: "Business Rule",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A rule of the business as a domain expert states it, before the model has placed it. Once placed it is either an invariant, when it must hold at all times for an aggregate or a value, or an assertion, when it is a post-condition of one operation. It is never recorded as its own section.",
					Sources: []Citation{
						{Work: "evans2015", Page: "22", Section: "Assertions"},
						{Work: "vernon2013", Chapter: 10, Page: "353"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "Recorded as an invariant or an assertion with one owner.",
				},
			},
			{
				Term:  "aggregate",
				Title: "Aggregate",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A cluster of entities and value objects with a boundary around it, treated as a single unit for the purpose of data changes. The one boundary is three things at once. It is a consistency boundary: properties and invariants are defined for the aggregate as a whole, the root enforces them, and inside the boundary consistency rules apply synchronously while across it updates are handled asynchronously. It is a transactional boundary: the aggregate is loaded, saved, and removed whole, one transaction changes one aggregate, and transactions do not cross the boundary. It is a reference boundary: one entity is the root, external objects hold references to the root only, a member's identity is local to the aggregate, and what one aggregate keeps of another is that aggregate's identity.",
					Sources: []Citation{
						{Work: "evans2015", Page: "16", Section: "Aggregates"},
						{Work: "fowler-aggregate"},
						{Work: "evans2003", Chapter: 6, Page: "127"},
						{Work: "vernon2013", Chapter: 10, Page: "347"},
					},
				},
				Records: Recording{
					Section: SectionAggregates,
					Note:    "A map keyed by the aggregate's name, which is the root's name; the entry is the root. The aggregate's code is where its root is declared: the package in Go, the file in TypeScript and Python.",
					Properties: []Property{
						{Name: "name", Required: true, Definition: "The aggregate's name, which is the name of its root entity and of the root's type in the code; the map key."},
						{Name: "definition", Required: true, Definition: "What the aggregate is and what changes together inside it."},
						{Name: "identity", Required: true, Definition: "The value object that is the root's global identity, a term of the context."},
						{Name: "aliases", Required: false, Definition: "Other names the team uses for the same term."},
						{Name: "entities", Required: false, Definition: "The aggregate's member entities other than the root, a map keyed by name; each has a local identity."},
						{Name: "invariants", Required: false, Definition: "The aggregate's invariants, a map from key to statement; each key names the rule, and ensure followed by the key names the root method that enforces it."},
						{Name: "assertions", Required: false, Definition: "Post-conditions of the root's operations, a map keyed by the assertion's name."},
						{Name: "repository", Required: false, Definition: "The name of the aggregate's repository type when the aggregate needs global access."},
						{Name: "factory", Required: false, Definition: "The name of the factory that assembles the aggregate when construction is complex."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "aggregate/one-root",
						Statement: "An aggregate entry is its root, an entity spelled with the aggregate's name and carrying the aggregate's identity; a name is never both an aggregate and a member entity, in its own aggregate or another.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "fowler-aggregate"},
							{Work: "vernon2013", Chapter: 10, Page: "380"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "aggregate/identity-recorded",
						Statement: "An aggregate names its identity, and the identity is a value object of the same context, recorded there or implied by the naming; an aggregate without an identity, or whose identity is recorded as anything but a value object, is rejected.",
						Sources: []Citation{
							{Work: "evans2015", Page: "11", Section: "Entities"},
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "vernon2013", Chapter: 5, Page: "173"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "aggregate/every-entity-has-an-aggregate",
						Statement: "Every entity is an aggregate or a member of exactly one aggregate; an entity recorded outside every aggregate is rejected, because the cluster with no boundary around it is what aggregates exist to prevent.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "aggregate/protects-an-invariant",
						Statement: "An aggregate records at least one invariant; a boundary drawn around nothing that must stay consistent is not yet justified, and the finding asks whether the entry is an aggregate or a value.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "vernon2013", Chapter: 10, Page: "353"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Languages: Languages{All: true},
							Severity:  severityWarning,
						},
					},
					{
						ID:        "aggregate/root-declared",
						Statement: "The root is one declared type spelled with the aggregate's name in the language's type case, found in the context's code; a type that can carry behaviour (a struct or named type in Go, a class in TypeScript and Python) is the root ahead of an interface or alias of the same name, two such declarations with nothing to choose between them are a finding, and none is a finding at the recording.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "evans2015", Page: "4", Section: "Ubiquitous Language"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "aggregate/invariants-enforced-by-root",
						Statement: "For every recorded invariant of the aggregate the root declares the method that enforces it, ensure followed by the key in the language's method case (EnsureLinesFrozen, ensureLinesFrozen, ensure_lines_frozen); the enforcement lives on the root and nowhere else.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "evans2015", Page: "20", Section: "Intention-Revealing Interfaces"},
							{Work: "vernon2013", Chapter: 10, Page: "354"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "aggregate/commands-named-for-behavior",
						Statement: "The root declares no method whose name begins with set; a change of state is a command named for what it does in the ubiquitous language, and a root made of setters is an anemic model whose rules live somewhere else.",
						Sources: []Citation{
							{Work: "evans2015", Page: "20", Section: "Intention-Revealing Interfaces"},
							{Work: "evans2015", Page: "21", Section: "Side-Effect-Free Functions"},
							{Work: "fowler-anemic-domain-model"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityWarning,
						},
					},
					{
						ID:        "aggregate/references-by-identity",
						Statement: "No constructor or command of one aggregate's root takes or returns another aggregate's root; what one aggregate needs of another it receives as an identity or a value. Field types are not yet observed, so a root held in a field is not seen, and an import alias hides a root of another package.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "fowler-aggregate"},
							{Work: "vernon2013", Chapter: 10, Page: "359"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations", "imports"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "aggregate/root-only-references",
						Statement: "Nothing outside the aggregate holds a reference to a member other than the root; references to members are passed out for use within a single operation only.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "fowler-aggregate"},
						},
						Enforcement: Enforcement{
							Facts:    []string{"declarations"},
							Needs:    "field-types",
							Severity: severityError,
						},
					},
					{
						ID:        "aggregate/one-per-transaction",
						Statement: "One transaction modifies one aggregate instance; transactions do not cross aggregate boundaries.",
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "fowler-aggregate"},
							{Work: "vernon2013", Chapter: 10, Page: "360"},
						},
						Enforcement: Enforcement{
							Needs:    "transaction-facts",
							Severity: severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Cluster into an aggregate what a true invariant requires to change atomically, and only that; a rule that only needs to hold eventually does not join two things into one aggregate.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "vernon2013", Chapter: 10, Page: "353"},
						},
					},
					{
						Text:        "Design small aggregates; do not cluster on the shape of the database or a parent-child relation, and reconsider the model when the boundaries are not guiding transactional and distributional decisions well.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "vernon2013", Chapter: 10, Page: "355"},
						},
					},
					{
						Text:        "Refer to another aggregate by its identity, never by holding its root.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "vernon2013", Chapter: 10, Page: "359"},
							{Work: "fowler-aggregate"},
						},
					},
					{
						Text:        "Use eventual consistency outside the boundary; across aggregates, handle updates asynchronously, and ask whose job it is to bring the other aggregate up to date.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "vernon2013", Chapter: 10, Page: "364"},
						},
					},
					{
						Text:        "Load, save, and remove an aggregate whole; a member shares its root's life cycle, is stored and deleted with it, and never outlives it.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "fowler-aggregate"},
							{Work: "evans2015", Page: "17", Section: "Repositories"},
							{Work: "evans2003", Chapter: 6, Page: "128"},
						},
					},
					{
						Text:        "Ask an aggregate whether something is allowed through a side-effect-free function named for the capability, or through a specification; a command changes state and returns no domain information.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "21", Section: "Side-Effect-Free Functions"},
							{Work: "evans-fowler-1997", Page: "2"},
						},
					},
					{
						Text: "Favor value object parts over entity parts inside an aggregate.",
						Sources: []Citation{
							{Work: "vernon2013", Chapter: 10, Page: "382"},
						},
					},
					{
						Text: "Tell the aggregate what to do rather than asking it for state and deciding outside it; follow the Law of Demeter.",
						Sources: []Citation{
							{Work: "vernon2013", Chapter: 10, Page: "382"},
						},
					},
					{
						Text:        "Keep an aggregate together on one server, and allow different aggregates to be distributed among nodes; where concurrent modification is possible, carry a version for optimistic concurrency.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "16", Section: "Aggregates"},
							{Work: "vernon2013", Chapter: 10, Page: "350"},
						},
					},
				},
			},
			{
				Term:  "aggregate_root",
				Title: "Aggregate Root",
				Phase: "tactical",
				Definition: Meaning{
					Text: "The one entity of an aggregate that external objects may hold references to, that carries the aggregate's globally unique identity, and that is responsible for enforcing the aggregate's invariants.",
					Sources: []Citation{
						{Work: "evans2015", Page: "16", Section: "Aggregates"},
						{Work: "fowler-aggregate"},
						{Work: "vernon2013", Chapter: 10, Page: "380"},
					},
				},
				Records: Recording{
					Section: SectionAggregates,
					Note:    "The root is the aggregate's entry itself; the aggregate's name is the root's name and the aggregate's identity is the root's.",
				},
			},
			{
				Term:  "domain_event",
				Title: "Domain Event",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A full-fledged part of the domain model representing something that happened in the domain that domain experts care about, as distinct from a system event. It is ordinarily immutable, being a record of the past, and typically carries the time it occurred and the identities of the entities involved.",
					Sources: []Citation{
						{Work: "evans2015", Page: "13", Section: "Domain Events"},
						{Work: "fowler-domain-event"},
						{Work: "vernon2013", Chapter: 8, Page: "285"},
					},
				},
				Records: Recording{
					Section: SectionEvents,
					Note:    "A map keyed by the event's name.",
					Properties: []Property{
						{Name: "name", Required: true, Definition: "The event's name, the name of its type in the code, phrased as something that happened; the map key."},
						{Name: "definition", Required: true, Definition: "What happened and who cares."},
						{Name: "raised_by", Required: false, Definition: "The aggregate whose operation raises it."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "domain_event/raised-by-an-aggregate",
						Statement: "An event that records what raises it names an aggregate of its own context; an event raised by a value object, a service, or a name the context does not record is rejected.",
						Sources: []Citation{
							{Work: "evans2015", Page: "13", Section: "Domain Events"},
							{Work: "vernon2013", Chapter: 8, Page: "287"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "domain_event/declared",
						Statement: "A recorded event is a declared type spelled with the event's name in the language's type case.",
						Sources: []Citation{
							{Work: "evans2015", Page: "13", Section: "Domain Events"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "domain_event/no-setters",
						Statement: "An event declares no method whose name begins with set; a record of the past is not edited.",
						Sources: []Citation{
							{Work: "evans2015", Page: "13", Section: "Domain Events"},
							{Work: "fowler-domain-event"},
							{Work: "vernon2013", Chapter: 8, Page: "291"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "domain_event/occurrence-time",
						Statement: "An event declares a field carrying the time it occurred.",
						Sources: []Citation{
							{Work: "evans2015", Page: "13", Section: "Domain Events"},
							{Work: "fowler-domain-event"},
							{Work: "vernon2013", Chapter: 8, Page: "291"},
						},
						Enforcement: Enforcement{
							Facts:     []string{"declarations"},
							Languages: Languages{Names: []string{"go", "typescript"}},
							Needs:     "field-declarations",
							Severity:  severityError,
						},
					},
					{
						ID:        "domain_event/immutable",
						Statement: "Every field of an event is immutable after construction.",
						Sources: []Citation{
							{Work: "evans2015", Page: "13", Section: "Domain Events"},
							{Work: "fowler-domain-event"},
						},
						Enforcement: Enforcement{
							Facts:    []string{"declarations"},
							Needs:    "field-mutability",
							Severity: severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text: "Name an event in the past tense for what happened, and name a time point clearly for which time it is, occurrence or notice.",
						Sources: []Citation{
							{Work: "fowler-domain-event"},
							{Work: "vernon2013", Chapter: 8, Page: "288"},
						},
					},
					{
						Text:        "Ignore irrelevant domain activity; make explicit the events the domain experts want to track or be notified of, or which are associated with state change in other model objects.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "13", Section: "Domain Events"},
						},
					},
				},
			},
			{
				Term:  "domain_service",
				Title: "Domain Service",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A standalone operation in the domain for a significant process or transformation that is not a natural responsibility of an entity or value object, declared as an interface with a name that is part of the ubiquitous language and a contract stated as assertions.",
					Sources: []Citation{
						{Work: "evans2015", Page: "14", Section: "Services"},
						{Work: "fowler-evans-classification"},
						{Work: "vernon2013", Chapter: 7, Page: "267"},
					},
				},
				Records: Recording{
					Section: SectionServices,
					Note:    "A map keyed by the service's name.",
					Properties: []Property{
						{Name: "name", Required: true, Definition: "The service's name, the name of its type in the code; the map key."},
						{Name: "definition", Required: true, Definition: "The process or transformation it performs and across which aggregates."},
					},
				},
				Invariants: []BlockInvariant{
					{
						ID:        "domain_service/declared",
						Statement: "A recorded service is a declared type spelled with the service's name in the language's type case.",
						Sources: []Citation{
							{Work: "evans2015", Page: "14", Section: "Services"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "domain_service/stateless",
						Statement: "A service declares no field that holds state across invocations.",
						Sources: []Citation{
							{Work: "evans2015", Page: "14", Section: "Services"},
							{Work: "vernon2013", Chapter: 7, Page: "268"},
						},
						Enforcement: Enforcement{
							Facts:     []string{"declarations"},
							Languages: Languages{Names: []string{"go", "typescript"}},
							Needs:     "field-declarations",
							Severity:  severityError,
						},
					},
					{
						ID:        "domain_service/not-injected-into-aggregates",
						Statement: "No constructor or command of an aggregate root takes a domain service as a parameter.",
						Sources: []Citation{
							{Work: "vernon2013", Chapter: 10, Page: "387"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorPlanned,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{Names: []string{"go", "typescript"}},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text: "Use a domain service for an operation that spans aggregates; look up what it needs ahead of invoking aggregate behavior rather than reaching out from inside the aggregate.",
						Sources: []Citation{
							{Work: "vernon2013", Chapter: 7, Page: "268"},
							{Work: "vernon2013", Chapter: 10, Page: "362"},
						},
					},
				},
			},
			{
				Term:  "application_service",
				Title: "Application Service",
				Phase: "tactical",
				Definition: Meaning{
					Text: "An operation of the application layer that coordinates a use case: it fetches aggregates through repositories, invokes their behavior, and commits, holding application logic that is not business logic and never the domain rules themselves.",
					Sources: []Citation{
						{Work: "evans2015", Page: "10", Section: "Layered Architecture"},
						{Work: "evans2015", Page: "17", Section: "Repositories"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "Application services are the use cases of the application Zone in rules.arclint.yaml; the domain file does not record them.",
				},
			},
			{
				Term:  "repository",
				Title: "Repository",
				Phase: "tactical",
				Definition: Meaning{
					Text: "For each type of aggregate that needs global access, a service that provides the illusion of an in-memory collection of all objects of that aggregate's root type, with methods to add and remove objects and to select them by criteria meaningful to domain experts, encapsulating the storage and query technology.",
					Sources: []Citation{
						{Work: "evans2015", Page: "17", Section: "Repositories"},
						{Work: "vernon2013", Chapter: 12, Page: "402"},
					},
				},
				Records: Recording{
					Section: SectionAggregates,
					Note:    "Recorded as the `repository` property of its aggregate; it has no entry of its own.",
				},
				Invariants: []BlockInvariant{
					{
						ID:        "repository/for-aggregate-roots-only",
						Statement: "A repository is recorded on an aggregate; a repository for an entity that is not an aggregate root, or for a value object, is rejected.",
						Sources: []Citation{
							{Work: "evans2015", Page: "17", Section: "Repositories"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorLoader,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "repository/declared",
						Statement: "A recorded repository is a declared type (interface, or class in a language without interfaces) spelled with the recorded name in the language's type case, declared in the context's code.",
						Sources: []Citation{
							{Work: "evans2015", Page: "17", Section: "Repositories"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "repository/not-called-from-aggregates",
						Statement: "No method of an aggregate root or of its members calls a repository.",
						Sources: []Citation{
							{Work: "vernon2013", Chapter: 7, Page: "266"},
							{Work: "vernon2013", Chapter: 10, Page: "387"},
						},
						Enforcement: Enforcement{
							Facts:    []string{"declarations", "calls"},
							Needs:    "resolved-calls",
							Severity: severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Provide repositories only for aggregate roots that actually need direct access; keep application logic focused on the model, delegating all object storage and access to the repositories.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "17", Section: "Repositories"},
						},
					},
				},
			},
			{
				Term:  "factory",
				Title: "Factory",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A separate object that encapsulates the creation of an entire, internally consistent aggregate, or of a complex value object, when construction becomes complicated or would reveal too much internal structure; it creates the whole as a piece, enforcing its invariants, without requiring the client to reference the concrete classes being instantiated.",
					Sources: []Citation{
						{Work: "evans2015", Page: "18", Section: "Factories"},
						{Work: "vernon2013", Chapter: 11, Page: "389"},
					},
				},
				Records: Recording{
					Section: SectionAggregates,
					Note:    "Recorded as the `factory` property of its aggregate; it has no entry of its own.",
				},
				Invariants: []BlockInvariant{
					{
						ID:        "factory/declared",
						Statement: "A recorded factory is a declared type or function spelled with the recorded name in the language's case, declared in the context's code.",
						Sources: []Citation{
							{Work: "evans2015", Page: "18", Section: "Factories"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorDomain,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
					{
						ID:        "factory/returns-the-aggregate",
						Statement: "A recorded factory's operations return the aggregate's root type.",
						Sources: []Citation{
							{Work: "evans2015", Page: "18", Section: "Factories"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorPlanned,
							Facts:     []string{"file_tree", "declarations"},
							Languages: Languages{Names: []string{"go", "typescript"}},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Create an entire aggregate as a piece, enforcing its invariants; create a complex value object as a piece, possibly after assembling the elements with a builder.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "18", Section: "Factories"},
						},
					},
				},
			},
			{
				Term:  "module",
				Title: "Module",
				Phase: "tactical",
				Definition: Meaning{
					Text: "A named partition of the code that tells the story of the system and contains a cohesive set of concepts, its name part of the ubiquitous language and reflecting insight into the domain, chosen so that the concepts inside can be understood and reasoned about independently.",
					Sources: []Citation{
						{Work: "evans2015", Page: "15", Section: "Modules"},
						{Work: "vernon2013", Chapter: 9, Page: "337"},
					},
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "A Module is a partition of the model, and arclint's partition of the code is the Zone. The domain file records nothing for it: an aggregate's code is the package or file its root is declared in, and a context's code is what its recorded terms are declared in.",
				},
				Invariants: []BlockInvariant{
					{
						ID:        "module/named-for-the-domain",
						Statement: "A package or file that declares an aggregate's root, or a Zone spelled with a context's name, is spelled in the ubiquitous language.",
						Sources: []Citation{
							{Work: "evans2015", Page: "15", Section: "Modules"},
						},
						Enforcement: Enforcement{
							By:        EvaluatorPlanned,
							Languages: Languages{All: true},
							Severity:  severityError,
						},
					},
				},
				Guidance: []Guidance{
					{
						Text:        "Choose modules that tell the story of the system and contain a cohesive set of concepts, and give them names that become part of the ubiquitous language.",
						Fundamental: true,
						Sources: []Citation{
							{Work: "evans2015", Page: "15", Section: "Modules"},
						},
					},
					{
						Text: "When modules are coupled, look for a way to change the model to disentangle the concepts, or for an overlooked concept that might be the basis of a module that would bring the elements together.",
						Sources: []Citation{
							{Work: "evans2015", Page: "15", Section: "Modules"},
						},
					},
				},
			},
			{
				Term:  "zone",
				Title: "Zone",
				Phase: "structural",
				Definition: Meaning{
					Text: "A named, physical partition of the codebase resolved via file paths or directory boundaries. It acts as a jurisdictional area where a specific set of architectural rules, technology constraints, and dependency rules are strictly enforced.",
				},
				Records: Recording{
					Section: SectionNone,
					Note:    "Zones are declared in rules.arclint.yaml with the paths they own; the domain file never names one. A Zone spelled with a bounded context's name says the Zone is that context: its terms are looked for there alone and every file of the Zone is the context's code, which is needed when the repository declares a recorded term more than once or when files that declare no recorded term are still the context's.",
				},
			},
			{
				Term:  "question",
				Title: "Open Question",
				Phase: "structural",
				Definition: Meaning{
					Text: "Something about a bounded context's model that the team has not settled, recorded in the domain file in place of a guess so that the gap is visible and can be answered. A question is never a rule; arclint enforces nothing from it and reports it only when asked what is open.",
				},
				Records: Recording{
					Section: SectionQuestions,
					Note:    "A map from key to the question's text, under the context it is about; the loader rejects an empty key, a key that is not kebab-case, or empty text.",
					Properties: []Property{
						{Name: "key", Required: true, Definition: "The question's name in kebab-case, unique within its context; the map key."},
						{Name: "text", Required: true, Definition: "The question, as the team would ask a domain expert."},
					},
				},
			},
		},
	}
}
