// Command genmetamodel generates the Go table of the Domain-Driven Design
// meta-model from metamodel.arclint.yaml. The YAML is the source the
// language is written in; the table is what the binary carries, so the
// domain package stays stdlib-only and no YAML is parsed at run time. The
// transcription is faithful and strict: an unknown key, a key recorded
// twice, or a value of the wrong shape refuses generation, and the
// semantic rules of the meta-model (citations resolve, ids are prefixed
// by their block, milestones and invariants name each other) are judged
// by the domain package's own validation, which a test applies to the
// generated table.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	in := flag.String("in", "metamodel.arclint.yaml", "meta-model YAML to transcribe")
	out := flag.String("out", "metamodel_gen.go", "output file")
	pkg := flag.String("pkg", "vocab", "package name")
	flag.Parse()

	src, err := os.ReadFile(*in)
	if err != nil {
		log.Fatal(err)
	}
	table, err := render(src, filepath.Base(*in), *pkg)
	if err != nil {
		log.Fatalf("%s: %v", *in, err)
	}
	// go generate runs in the package directory and the table lives beside
	// its YAML; the write is confined to that directory so no -out value can
	// reach outside the package.
	pkgDir, err := os.OpenRoot(".")
	if err != nil {
		log.Fatal(err)
	}
	if err := pkgDir.WriteFile(*out, table, 0o600); err != nil {
		log.Fatal(err)
	}
	if err := pkgDir.Close(); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s from %s\n", *out, *in)
}

// render transcribes the meta-model YAML into the Go source of the table.
func render(src []byte, sourceName, pkg string) ([]byte, error) {
	doc, err := parse(src)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	e := emitter{w: &b}
	e.printf("// Code generated by tools/genmetamodel from %s; DO NOT EDIT.\n\n", sourceName)
	e.printf("package %s\n\n", pkg)
	e.printf("// ddd is the generated Domain-Driven Design meta-model; DDD returns it.\n")
	e.printf("func ddd() MetaModel {\n")
	e.printf("return MetaModel{\n")
	e.printf("Name: %q,\n", doc.Name)
	e.printf("Title: %q,\n", doc.Title)
	e.printf("Description: %q,\n", doc.Description)
	e.works(doc.Works)
	e.facts(doc.Facts)
	e.milestones(doc.Milestones)
	e.phases(doc.Phases)
	e.blocks(doc.Blocks)
	e.printf("}\n}\n")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("generated source does not format: %w", err)
	}
	return formatted, nil
}

// The document mirrors metamodel.arclint.yaml key for key. Sections that
// the file writes as maps keyed by name decode through ordered, which
// keeps file order and refuses a key written twice.

type document struct {
	Version     int                `yaml:"version"`
	Name        string             `yaml:"name"`
	Title       string             `yaml:"title"`
	Description string             `yaml:"description"`
	Works       ordered[work]      `yaml:"works"`
	Facts       ordered[fact]      `yaml:"facts"`
	Milestones  ordered[milestone] `yaml:"milestones"`
	Phases      []phase            `yaml:"phases"`
	Blocks      []block            `yaml:"building_blocks"`
}

type work struct {
	Title        string   `yaml:"title"`
	Author       string   `yaml:"author"`
	Authors      []string `yaml:"authors"`
	Publisher    string   `yaml:"publisher"`
	Year         int      `yaml:"year"`
	Date         string   `yaml:"date"`
	ISBN         string   `yaml:"isbn"`
	URL          string   `yaml:"url"`
	License      string   `yaml:"license"`
	Verification string   `yaml:"verification"`
}

type fact struct {
	Definition string    `yaml:"definition"`
	Languages  languages `yaml:"languages"`
}

type milestone struct {
	Needs   string   `yaml:"needs"`
	Unlocks []string `yaml:"unlocks"`
}

type phase struct {
	Name       string  `yaml:"name"`
	Title      string  `yaml:"title"`
	Definition meaning `yaml:"definition"`
}

type meaning struct {
	Text    string     `yaml:"text"`
	Sources []citation `yaml:"sources"`
}

type citation struct {
	Work    string `yaml:"work"`
	Chapter int    `yaml:"chapter"`
	Page    string `yaml:"page"`
	Section string `yaml:"section"`
}

type block struct {
	Term       string      `yaml:"term"`
	Title      string      `yaml:"title"`
	Phase      string      `yaml:"phase"`
	Definition meaning     `yaml:"definition"`
	Records    recording   `yaml:"records"`
	Invariants []invariant `yaml:"invariants"`
	Guidance   []guidance  `yaml:"guidance"`
}

type recording struct {
	Section    string     `yaml:"section"`
	Note       string     `yaml:"note"`
	Properties []property `yaml:"properties"`
	Kinds      []kind     `yaml:"kinds"`
}

type property struct {
	Name       string `yaml:"name"`
	Required   bool   `yaml:"required"`
	Definition string `yaml:"definition"`
}

type kind struct {
	Name       string     `yaml:"name"`
	Definition string     `yaml:"definition"`
	Sources    []citation `yaml:"sources"`
}

type invariant struct {
	ID          string      `yaml:"id"`
	Statement   string      `yaml:"statement"`
	Sources     []citation  `yaml:"sources"`
	Enforcement enforcement `yaml:"enforcement"`
}

type enforcement struct {
	By        string    `yaml:"by"`
	Facts     []string  `yaml:"facts"`
	Languages languages `yaml:"languages"`
	Needs     string    `yaml:"needs"`
	Severity  string    `yaml:"severity"`
}

type guidance struct {
	Text        string     `yaml:"text"`
	Fundamental bool       `yaml:"fundamental"`
	Sources     []citation `yaml:"sources"`
}

// languages is the scalar `all` or a sequence of language names.
type languages struct {
	All   bool
	Names []string
}

func (l *languages) UnmarshalYAML(value *yaml.Node) error {
	switch value.Kind {
	case yaml.ScalarNode:
		if value.Value != "all" {
			return fmt.Errorf("line %d: languages must be all or a list of languages, got %q", value.Line, value.Value)
		}
		*l = languages{All: true}
		return nil
	case yaml.SequenceNode:
		var names []string
		if err := value.Decode(&names); err != nil {
			return fmt.Errorf("line %d: languages: %w", value.Line, err)
		}
		*l = languages{Names: names}
		return nil
	default:
		return fmt.Errorf("line %d: languages must be all or a list of languages", value.Line)
	}
}

// ordered is a YAML mapping decoded in file order with duplicate keys
// refused and unknown fields in every value refused.
type ordered[T any] struct {
	Keys   []string
	Values map[string]T
}

func (o *ordered[T]) UnmarshalYAML(value *yaml.Node) error {
	if value.Kind != yaml.MappingNode {
		return fmt.Errorf("line %d: expected a mapping keyed by name", value.Line)
	}
	o.Values = map[string]T{}
	for i := 0; i+1 < len(value.Content); i += 2 {
		keyNode, valueNode := value.Content[i], value.Content[i+1]
		key := keyNode.Value
		if _, dup := o.Values[key]; dup {
			return fmt.Errorf("line %d: key %q already recorded", keyNode.Line, key)
		}
		var v T
		if err := decodeStrict(valueNode, &v); err != nil {
			return fmt.Errorf("%q: %w", key, err)
		}
		o.Keys = append(o.Keys, key)
		o.Values[key] = v
	}
	return nil
}

// decodeStrict decodes one node with unknown fields refused. A Node's own
// Decode has no KnownFields switch, so the node is re-encoded and read
// back through a strict decoder.
func decodeStrict(node *yaml.Node, out any) error {
	raw, err := yaml.Marshal(node)
	if err != nil {
		return fmt.Errorf("line %d: %w", node.Line, err)
	}
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	if err := dec.Decode(out); err != nil {
		return fmt.Errorf("line %d: %w", node.Line, err)
	}
	return nil
}

// The closed vocabularies the file writes as words and the table writes
// as the vocab package's identifiers, so the table carries no repeated
// literal and a word outside the set refuses generation.
var (
	verifications = map[string]string{
		"text":    "VerifiedText",
		"fetched": "VerifiedFetched",
		"carried": "VerifiedCarried",
	}
	evaluators = map[string]string{
		"loader":  "EvaluatorLoader",
		"domain":  "EvaluatorDomain",
		"planned": "EvaluatorPlanned",
	}
	sections = map[string]string{
		"top":            "SectionTop",
		"none":           "SectionNone",
		"contexts":       "SectionContexts",
		"relations":      "SectionRelations",
		"entities":       "SectionEntities",
		"value_objects":  "SectionValueObjects",
		"invariants":     "SectionInvariants",
		"assertions":     "SectionAssertions",
		"specifications": "SectionSpecifications",
		"aggregates":     "SectionAggregates",
		"events":         "SectionEvents",
		"services":       "SectionServices",
		"questions":      "SectionQuestions",
	}
	severities = map[string]string{
		"":        "severityError",
		"error":   "severityError",
		"warning": "severityWarning",
	}
)

func parse(src []byte) (document, error) {
	dec := yaml.NewDecoder(bytes.NewReader(src))
	dec.KnownFields(true)
	var doc document
	if err := dec.Decode(&doc); err != nil {
		return document{}, fmt.Errorf("meta-model: %w", err)
	}
	if doc.Version != 1 {
		return document{}, fmt.Errorf("version %d is not the meta-model version this generator transcribes (1)", doc.Version)
	}
	var problems []error
	for _, key := range doc.Works.Keys {
		w := doc.Works.Values[key]
		if w.Author != "" && len(w.Authors) > 0 {
			problems = append(problems, fmt.Errorf("works %q: write author or authors, not both", key))
		}
		if _, ok := verifications[w.Verification]; !ok {
			problems = append(problems, fmt.Errorf("works %q: verification %q is not text, fetched, or carried", key, w.Verification))
		}
	}
	for _, b := range doc.Blocks {
		if _, ok := sections[b.Records.Section]; !ok {
			problems = append(problems, fmt.Errorf("building block %s: records.section %q is not a published section, top, or none", b.Term, b.Records.Section))
		}
		for _, inv := range b.Invariants {
			if _, ok := severities[inv.Enforcement.Severity]; !ok {
				problems = append(problems, fmt.Errorf("invariant %s: severity %q is not error or warning", inv.ID, inv.Enforcement.Severity))
			}
			if by := inv.Enforcement.By; by != "" {
				if _, ok := evaluators[by]; !ok {
					problems = append(problems, fmt.Errorf("invariant %s: evaluator %q is not published", inv.ID, by))
				}
			}
		}
	}
	return doc, errors.Join(problems...)
}

// emitter writes the table's Go source; gofmt settles the indentation.
type emitter struct {
	w *bytes.Buffer
}

func (e emitter) printf(format string, args ...any) {
	fmt.Fprintf(e.w, format, args...)
}

func (e emitter) strings(field string, values []string) {
	if len(values) == 0 {
		return
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = strconv.Quote(v)
	}
	e.printf("%s: []string{%s},\n", field, strings.Join(quoted, ", "))
}

func (e emitter) str(field, value string) {
	if value == "" {
		return
	}
	e.printf("%s: %q,\n", field, value)
}

func (e emitter) works(ws ordered[work]) {
	e.printf("Works: []Work{\n")
	for _, key := range ws.Keys {
		w := ws.Values[key]
		authors := w.Authors
		if w.Author != "" {
			authors = []string{w.Author}
		}
		e.printf("{\n")
		e.str("Key", key)
		e.str("Title", w.Title)
		e.strings("Authors", authors)
		e.str("Publisher", w.Publisher)
		if w.Year != 0 {
			e.printf("Year: %d,\n", w.Year)
		}
		e.str("Date", w.Date)
		e.str("ISBN", w.ISBN)
		e.str("URL", w.URL)
		e.str("License", w.License)
		e.printf("Verification: %s,\n", verifications[w.Verification])
		e.printf("},\n")
	}
	e.printf("},\n")
}

func (e emitter) facts(fs ordered[fact]) {
	e.printf("Facts: []FactDefinition{\n")
	for _, key := range fs.Keys {
		f := fs.Values[key]
		e.printf("{\n")
		e.str("Name", key)
		e.str("Definition", f.Definition)
		e.languages(f.Languages)
		e.printf("},\n")
	}
	e.printf("},\n")
}

func (e emitter) milestones(ms ordered[milestone]) {
	e.printf("Milestones: []Milestone{\n")
	for _, key := range ms.Keys {
		m := ms.Values[key]
		e.printf("{\n")
		e.str("Key", key)
		e.str("Needs", m.Needs)
		e.strings("Unlocks", m.Unlocks)
		e.printf("},\n")
	}
	e.printf("},\n")
}

func (e emitter) phases(ps []phase) {
	e.printf("Phases: []Phase{\n")
	for _, p := range ps {
		e.printf("{\n")
		e.str("Name", p.Name)
		e.str("Title", p.Title)
		e.meaning("Definition", p.Definition)
		e.printf("},\n")
	}
	e.printf("},\n")
}

func (e emitter) blocks(bs []block) {
	e.printf("Blocks: []BuildingBlock{\n")
	for _, b := range bs {
		e.printf("{\n")
		e.str("Term", b.Term)
		e.str("Title", b.Title)
		e.str("Phase", b.Phase)
		e.meaning("Definition", b.Definition)
		e.recording(b.Records)
		e.invariants(b.Invariants)
		e.guidance(b.Guidance)
		e.printf("},\n")
	}
	e.printf("},\n")
}

func (e emitter) meaning(field string, m meaning) {
	e.printf("%s: Meaning{\n", field)
	e.str("Text", m.Text)
	e.citations(m.Sources)
	e.printf("},\n")
}

func (e emitter) citations(cs []citation) {
	if len(cs) == 0 {
		return
	}
	e.printf("Sources: []Citation{\n")
	for _, c := range cs {
		e.printf("{")
		parts := []string{fmt.Sprintf("Work: %q", c.Work)}
		if c.Chapter != 0 {
			parts = append(parts, fmt.Sprintf("Chapter: %d", c.Chapter))
		}
		if c.Page != "" {
			parts = append(parts, fmt.Sprintf("Page: %q", c.Page))
		}
		if c.Section != "" {
			parts = append(parts, fmt.Sprintf("Section: %q", c.Section))
		}
		e.printf("%s", strings.Join(parts, ", "))
		e.printf("},\n")
	}
	e.printf("},\n")
}

func (e emitter) recording(r recording) {
	e.printf("Records: Recording{\n")
	e.printf("Section: %s,\n", sections[r.Section])
	e.str("Note", r.Note)
	if len(r.Properties) > 0 {
		e.printf("Properties: []Property{\n")
		for _, p := range r.Properties {
			e.printf("{Name: %q, Required: %t, Definition: %q},\n", p.Name, p.Required, p.Definition)
		}
		e.printf("},\n")
	}
	if len(r.Kinds) > 0 {
		e.printf("Kinds: []KindDefinition{\n")
		for _, k := range r.Kinds {
			e.printf("{\n")
			e.str("Name", k.Name)
			e.str("Definition", k.Definition)
			e.citations(k.Sources)
			e.printf("},\n")
		}
		e.printf("},\n")
	}
	e.printf("},\n")
}

func (e emitter) invariants(is []invariant) {
	if len(is) == 0 {
		return
	}
	e.printf("Invariants: []BlockInvariant{\n")
	for _, inv := range is {
		e.printf("{\n")
		e.str("ID", inv.ID)
		e.str("Statement", inv.Statement)
		e.citations(inv.Sources)
		e.enforcement(inv.Enforcement)
		e.printf("},\n")
	}
	e.printf("},\n")
}

func (e emitter) enforcement(en enforcement) {
	e.printf("Enforcement: Enforcement{\n")
	if en.By != "" {
		e.printf("By: %s,\n", evaluators[en.By])
	}
	e.strings("Facts", en.Facts)
	e.languages(en.Languages)
	e.str("Needs", en.Needs)
	e.printf("Severity: %s,\n", severities[en.Severity])
	e.printf("},\n")
}

func (e emitter) languages(l languages) {
	switch {
	case l.All:
		e.printf("Languages: Languages{All: true},\n")
	case len(l.Names) > 0:
		quoted := make([]string, len(l.Names))
		for i, n := range l.Names {
			quoted[i] = strconv.Quote(n)
		}
		e.printf("Languages: Languages{Names: []string{%s}},\n", strings.Join(quoted, ", "))
	}
}

func (e emitter) guidance(gs []guidance) {
	if len(gs) == 0 {
		return
	}
	e.printf("Guidance: []Guidance{\n")
	for _, g := range gs {
		e.printf("{\n")
		e.str("Text", g.Text)
		if g.Fundamental {
			e.printf("Fundamental: true,\n")
		}
		e.citations(g.Sources)
		e.printf("},\n")
	}
	e.printf("},\n")
}
