package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const vocabDir = "../../internal/domain/vocab"

// The committed table must be what the generator writes from the
// committed YAML; edit the YAML, run go generate, commit both.
func TestGeneratedTableIsCurrent(t *testing.T) {
	src, err := os.ReadFile(filepath.Join(vocabDir, "metamodel.arclint.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	want, err := os.ReadFile(filepath.Join(vocabDir, "metamodel_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	got, err := render(src, "metamodel.arclint.yaml", "vocab")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatal("metamodel_gen.go is stale: run `go generate ./internal/domain/vocab/`")
	}
}

const minimal = `version: 1
name: ddd
title: Domain-Driven Design
description: The vocabulary.
works:
  evans2015:
    title: Reference
    author: Eric Evans
    year: 2015
    verification: text
facts:
  declarations:
    definition: Declarations.
    languages: all
milestones: {}
phases:
  - name: tactical
    title: Tactical design
    definition:
      text: Blocks.
      sources: [{work: evans2015, page: 9}]
building_blocks:
  - term: aggregate
    title: Aggregate
    phase: tactical
    definition:
      text: A cluster.
      sources: [{work: evans2015, page: 16, section: Aggregates}]
    records:
      section: aggregates
      properties:
        - {name: identity, required: true, definition: "The root's identity, a value object."}
    invariants:
      - id: aggregate/root-declared
        statement: The root is declared.
        sources: [{work: evans2015, page: 16}]
        enforcement: {by: planned, facts: [declarations], languages: [go, typescript]}
`

func TestRenderTranscribesMinimalDocument(t *testing.T) {
	got, err := render([]byte(minimal), "minimal.yaml", "vocab")
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	// gofmt aligns field values, so compare with runs of blanks folded.
	out := strings.Join(strings.Fields(string(got)), " ")
	for _, want := range []string{
		`// Code generated by tools/genmetamodel from minimal.yaml; DO NOT EDIT.`,
		`Authors: []string{"Eric Evans"}`,
		`Languages: Languages{All: true}`,
		`{Name: "identity", Required: true, Definition: "The root's identity, a value object."}`,
		`{Work: "evans2015", Page: "16", Section: "Aggregates"}`,
		`Verification: VerifiedText`,
		`Section: SectionAggregates`,
		`By: EvaluatorPlanned`,
		`Languages: Languages{Names: []string{"go", "typescript"}}`,
		`Severity: severityError`,
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output lacks %q:\n%s", want, got)
		}
	}
}

func TestRenderRefusesUnknownKeys(t *testing.T) {
	src := strings.Replace(minimal, "enforcement: {by: planned,", "enforcement: {level: check, by: planned,", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), "level") {
		t.Fatalf("level is derived, never recorded; got %v", err)
	}
}

// A flow-mapping definition with an unquoted comma splits into a second
// key; the strict decoder names it instead of dropping the tail.
func TestRenderRefusesCommaSplitDefinition(t *testing.T) {
	src := strings.Replace(minimal,
		`definition: "The root's identity, a value object."`,
		`definition: The root's identity, a value object.`, 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), "a value object") {
		t.Fatalf("expected the split tail to be reported as an unknown field; got %v", err)
	}
}

func TestRenderRefusesDuplicateKeys(t *testing.T) {
	src := strings.Replace(minimal, "facts:\n", "facts:\n  declarations:\n    definition: Twice.\n    languages: all\n", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), `"declarations" already recorded`) {
		t.Fatalf("expected the duplicate fact to be refused; got %v", err)
	}
}

func TestRenderRefusesBothAuthorSpellings(t *testing.T) {
	src := strings.Replace(minimal, "    author: Eric Evans\n", "    author: Eric Evans\n    authors: [Eric Evans]\n", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), "author or authors") {
		t.Fatalf("expected author/authors conflict; got %v", err)
	}
}

func TestRenderRefusesUnknownSeverity(t *testing.T) {
	src := strings.Replace(minimal, "languages: [go, typescript]}", "languages: [go, typescript], severity: info}", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), `severity "info"`) {
		t.Fatalf("expected severity refusal; got %v", err)
	}
}

func TestRenderRefusesLanguagesScalarOtherThanAll(t *testing.T) {
	src := strings.Replace(minimal, "languages: all", "languages: every", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), "languages must be all") {
		t.Fatalf("expected languages refusal; got %v", err)
	}
}

func TestRenderRefusesUnknownSection(t *testing.T) {
	src := strings.Replace(minimal, "section: aggregates", "section: roots", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), `records.section "roots"`) {
		t.Fatalf("expected section refusal; got %v", err)
	}
}

func TestRenderRefusesUnknownEvaluator(t *testing.T) {
	src := strings.Replace(minimal, "by: planned", "by: oracle", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), `evaluator "oracle"`) {
		t.Fatalf("expected evaluator refusal; got %v", err)
	}
}

func TestRenderRefusesUnknownVerification(t *testing.T) {
	src := strings.Replace(minimal, "verification: text", "verification: trusted", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), `verification "trusted"`) {
		t.Fatalf("expected verification refusal; got %v", err)
	}
}

func TestRenderRefusesOtherVersions(t *testing.T) {
	src := strings.Replace(minimal, "version: 1", "version: 2", 1)
	_, err := render([]byte(src), "minimal.yaml", "vocab")
	if err == nil || !strings.Contains(err.Error(), "version 2") {
		t.Fatalf("expected version refusal; got %v", err)
	}
}
