// Command gensdktypes generates the TypeScript declarations of the
// host/extension wire types via tygo, so arclint.d.ts can never drift
// from the Go host structs.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strconv"

	"github.com/gzuidhof/tygo/tygo"
)

func main() {
	if err := generate("sdk/types_gen.ts"); err != nil {
		log.Fatal(err)
	}
	log.Println("wrote sdk/types_gen.ts")
	if err := generateAPI("sdkinit.go", "sdk/api_gen.ts"); err != nil {
		log.Fatal(err)
	}
	log.Println("wrote sdk/api_gen.ts")
}

// Read the literal without importing the runtime package or requiring its
// generated artifacts to compile. SDKInit consumes the same literal directly.
func generateAPI(source, output string) error {
	file, err := parser.ParseFile(token.NewFileSet(), source, nil, 0)
	if err != nil {
		return fmt.Errorf("read SDK contract: %w", err)
	}
	for _, decl := range file.Decls {
		group, ok := decl.(*ast.GenDecl)
		if !ok || group.Tok != token.CONST {
			continue
		}
		for _, spec := range group.Specs {
			value, ok := spec.(*ast.ValueSpec)
			if !ok || len(value.Names) != 1 || value.Names[0].Name != "sdkAPIDecl" {
				continue
			}
			if len(value.Values) != 1 {
				return fmt.Errorf("SDK contract sdkAPIDecl must be a string literal")
			}
			literal, ok := value.Values[0].(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				return fmt.Errorf("SDK contract sdkAPIDecl must be a string literal")
			}
			contract, err := strconv.Unquote(literal.Value)
			if err != nil {
				return fmt.Errorf("decode SDK contract: %w", err)
			}
			const header = "// Code generated by tools/gensdktypes from sdkinit.go; DO NOT EDIT.\n"
			if err := os.WriteFile(output, []byte(header+contract), 0o600); err != nil {
				return fmt.Errorf("write SDK contract: %w", err)
			}
			return nil
		}
	}
	return fmt.Errorf("SDK contract sdkAPIDecl not found in %s", source)
}

func generate(output string) error {
	cfg := &tygo.Config{
		Packages: []*tygo.PackageConfig{{
			Path:         "github.com/wixregiga/arclint/internal/infrastructure/extension/sobek",
			OutputPath:   output,
			IncludeFiles: []string{"types.go"},
			Frontmatter:  "// Code generated by tools/gensdktypes (tygo) from the sobek extension host types; DO NOT EDIT.\n",
		}},
	}
	if err := tygo.New(cfg).Generate(); err != nil {
		return fmt.Errorf("generate SDK wire types: %w", err)
	}
	return nil
}
