// Command gensdktypes generates the TypeScript declarations of the
// host/extension wire types via tygo, so arclint.d.ts can never drift
// from the Go host structs.
package main

import (
	"log"

	"github.com/gzuidhof/tygo/tygo"
)

func main() {
	cfg := &tygo.Config{
		Packages: []*tygo.PackageConfig{{
			Path:         "github.com/wixregiga/arclint/internal/infrastructure/extension/sobek",
			OutputPath:   "sdk/types_gen.ts",
			IncludeFiles: []string{"types.go"},
			Frontmatter:  "// Code generated by tools/gensdktypes (tygo) from the sobek extension host types; DO NOT EDIT.\n",
		}},
	}
	if err := tygo.New(cfg).Generate(); err != nil {
		log.Fatal(err)
	}
	log.Println("wrote sdk/types_gen.ts")
}
