// Command genpystdlib generates the embedded Python standard-library
// module table from sys.stdlib_module_names of the CPython invoked at
// generate time: the authoritative source (PEP 632 era, 3.10+).
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"sort"
)

func main() {
	out := flag.String("out", "stdlib_gen.go", "output file")
	pkg := flag.String("pkg", "python", "package name")
	flag.Parse()

	raw, err := exec.CommandContext(context.Background(), "python3", "-c",
		"import sys, json; print(json.dumps({'version': sys.version.split()[0], 'modules': sorted(sys.stdlib_module_names)}))").Output()
	if err != nil {
		log.Fatalf("python3 stdlib_module_names: %v (Python is required at generate time only)", err)
	}
	var payload struct {
		Version string   `json:"version"`
		Modules []string `json:"modules"`
	}
	if err := json.Unmarshal(bytes.TrimSpace(raw), &payload); err != nil {
		log.Fatalf("parse: %v", err)
	}
	// Private stdlib modules (_abc, _ast) stay in the table: importing
	// them is stdlib consumption, and exact membership beats pruning.
	modules := payload.Modules
	sort.Strings(modules)
	if len(modules) < 150 {
		log.Fatalf("only %d modules; expected the full stdlib set", len(modules))
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/genpystdlib; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: sys.stdlib_module_names of CPython %s.\n\n", payload.Version)
	fmt.Fprintf(&b, "package %s\n\n", *pkg)
	fmt.Fprintf(&b, "// StdlibToolchain is the CPython version whose stdlib_module_names produced the table.\n")
	fmt.Fprintf(&b, "const StdlibToolchain = %q\n\n", "python"+payload.Version)
	fmt.Fprintf(&b, "var pyStdlib = map[string]struct{}{\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%q: {},\n", m)
	}
	fmt.Fprintf(&b, "}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o600); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s: %d modules (python %s)\n", *out, len(modules), payload.Version)
}
