// Code generated by tygo. DO NOT EDIT.
// Code generated by tools/gensdktypes (tygo) from internal/ext/types.go; DO NOT EDIT.

//////////
// source: types.go
/*
Package ext implements the TypeScript extension SDK: discovery under
.arclint/extensions/, in-process transpilation via esbuild, execution on
sobek (the k6 pattern), a two-phase register-then-run lifecycle, and a
sandbox with no ambient I/O.

The types in this file are the host/extension wire contract. The
TypeScript declarations rule authors see are generated from these
structs (tools/gensdktypes, via tygo), so the .d.ts can never drift from
the host.
*/

/**
 * FileInfo is one repository file as exposed to ctx.files().
 */
export interface FileInfo {
  path: string;
  name: string;
  stem: string;
  ext: string;
  dir: string;
  size: number /* int */;
}
/**
 * ImportInfo is one classified import occurrence as exposed to
 * ctx.imports(path), for every active language target.
 */
export interface ImportInfo {
  path: string;
  line: number /* int */;
  /**
   * Class is stdlib | internal | external | unknown | cgo.
   */
  class: string;
  /**
   * TargetDir is the repo-relative package directory for internal
   * imports resolved into the tree, else "".
   */
  targetDir: string;
  /**
   * TargetFile is the repo-relative file an internal import resolves to
   * for file-granular languages (JS/TS, Python), else "".
   */
  targetFile: string;
}
/**
 * DeclInfo is one declaration as exposed through ctx.facts(path).
 */
export interface DeclInfo {
  /**
   * Kind is a small cross-language vocabulary: struct, interface,
   * type, class, enum, func, method, field, const, var.
   */
  kind: string;
  name: string;
  /**
   * Owner names the enclosing declaration for members (receiver type,
   * interface, class, enclosing function), else "".
   */
  owner: string;
  /**
   * Exported: Go identifier case, TS export/accessibility modifiers,
   * Python leading-underscore convention.
   */
  exported: boolean;
  startLine: number /* int */;
  endLine: number /* int */;
}
/**
 * FactsInfo is the declaration-fact view of one file as exposed to
 * ctx.facts(path). A file that failed to parse has empty decls and a
 * non-empty parseError; rules see absence, never a crash.
 */
export interface FactsInfo {
  path: string;
  /**
   * Package is the Go package clause; "" for other languages.
   */
  package: string;
  decls: DeclInfo[];
  parseError?: string;
}
/**
 * ViolationInput is what ctx.report() accepts from a rule.
 */
export interface ViolationInput {
  path: string;
  message: string;
  line?: number /* int */;
  fixHint?: string;
  /**
   * Severity overrides the instance severity: error | warn | info.
   */
  severity?: string;
  /**
   * Contract overrides the rule type's contract clause for this one
   * finding: consumes | provides | invariant. A rule that enforces both
   * sides of a contract labels each finding truthfully.
   */
  contract?: string;
  /**
   * Blame overrides the rule type's blame side for this one finding:
   * consumer | provider.
   */
  blame?: string;
}
