// Command gendocs renders the docs-site rule reference from the single
// source of rule-type documentation (internal/config/ruledoc.go). The
// terminal (`arclint explain`), the JSON Schema hovers, and the site page
// all read the same strings, so they cannot drift; a test asserts the
// committed page matches this generator's output.
package main

import (
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/wixregiga/arclint/internal/config"
)

const outPath = "../../docs/site/content/docs/rules.md"

func render() []byte {
	var b strings.Builder
	b.WriteString(`+++
title = "Rule reference"
description = "Every builtin rule kind: what it means, where it goes, a paste-ready example."
weight = 3
+++

<!-- Generated by tools/gendocs from internal/config/ruledoc.go; DO NOT EDIT.
     Regenerate with: go generate ./tools/gendocs -->

The same text serves ` + "`arclint explain <kind>`" + ` and the JSON Schema
hovers in your editor.
`)
	for _, d := range config.RuleDocs {
		fmt.Fprintf(&b, "\n## %s\n\n", d.Kind)
		fmt.Fprintf(&b, "%s\n\n", d.Summary)
		fmt.Fprintf(&b, "- where: `%s`\n", d.Where)
		if d.Clause != "" {
			fmt.Fprintf(&b, "- clause: `%s`, blame: `%s`\n", d.Clause, d.Blame)
		}
		if capability := config.CapabilityOf(d.Kind); capability != "" {
			fmt.Fprintf(&b, "- capability: `%s`\n", capability)
		}
		fmt.Fprintf(&b, "\n%s\n\n```yaml\n%s\n```\n", d.Doc, strings.TrimRight(d.Example, "\n"))
	}
	return []byte(b.String())
}

//go:generate go run .

func main() {
	if err := os.WriteFile(outPath, render(), 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %s", outPath)
}
