// Command gennodestdlib generates the embedded Node.js builtin-module
// table from `node -p require('module').builtinModules` of the toolchain
// running go:generate — the authoritative source, not a curated list.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"sort"
	"strings"
)

func main() {
	out := flag.String("out", "stdlib_gen.go", "output file")
	pkg := flag.String("pkg", "jsts", "package name")
	flag.Parse()

	verRaw, err := exec.Command("node", "--version").Output()
	if err != nil {
		log.Fatalf("node --version: %v (Node is required at generate time only)", err)
	}
	version := strings.TrimSpace(string(verRaw))

	raw, err := exec.Command("node", "-p", "JSON.stringify(require('module').builtinModules)").Output()
	if err != nil {
		log.Fatalf("node builtinModules: %v", err)
	}
	var mods []string
	if err := json.Unmarshal(bytes.TrimSpace(raw), &mods); err != nil {
		log.Fatalf("parse: %v", err)
	}
	var clean []string
	for _, m := range mods {
		// The list contains both bare and node:-prefixed names; the table
		// stores bare names and the classifier strips the node: prefix.
		if s, ok := strings.CutPrefix(m, "node:"); ok {
			m = s
		}
		clean = append(clean, m)
	}
	sort.Strings(clean)
	clean = dedupe(clean)
	if len(clean) < 30 {
		log.Fatalf("only %d builtins; expected the full Node builtin set", len(clean))
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/gennodestdlib; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: require('module').builtinModules of Node %s.\n\n", version)
	fmt.Fprintf(&b, "package %s\n\n", *pkg)
	fmt.Fprintf(&b, "// StdlibToolchain is the Node version whose builtinModules produced the table.\n")
	fmt.Fprintf(&b, "const StdlibToolchain = %q\n\n", version)
	fmt.Fprintf(&b, "var nodeBuiltins = map[string]struct{}{\n")
	for _, m := range clean {
		fmt.Fprintf(&b, "\t%q: {},\n", m)
	}
	fmt.Fprintf(&b, "}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s: %d builtins (%s)\n", *out, len(clean), version)
}

func dedupe(in []string) []string {
	var out []string
	for i, s := range in {
		if i == 0 || in[i-1] != s {
			out = append(out, s)
		}
	}
	return out
}
