package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/wixregiga/arclint/internal/config"
)

// Markers delimit the generated block inside AGENTS.md. Everything the
// user writes outside them survives every regeneration.
const (
	agentsBegin = "<!-- arclint:agents:begin -->"
	agentsEnd   = "<!-- arclint:agents:end -->"
)

// newAgentsCmd compiles the loaded ruleset into a compact, prompt-time
// architecture block for coding agents: the modules, their dependency
// policy, repo-wide rules, and the query commands. Print by default;
// --write installs or refreshes the block in <repo-root>/AGENTS.md
// between markers, leaving everything outside them untouched.
func newAgentsCmd() *cobra.Command {
	var rulesFlag string
	var write bool
	cmd := &cobra.Command{
		Use:   "agents",
		Short: "compile the ruleset into a generated AGENTS.md architecture block",
		Long: `Compiles rules.yaml into the compact architecture context an agent
needs at prompt time: every module with its purpose and dependency
policy, repo-wide extension rules, and the commands that answer deeper
questions. Prints the block by default; --write installs or refreshes
it in <repo-root>/AGENTS.md between begin/end markers. Content outside
the markers is never touched, so the file can carry hand-written
instructions alongside the generated block.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			rs, err := loadForRead(rulesFlag)
			if err != nil {
				return err
			}
			var repoRules []config.RuleInstance
			if len(rs.Rules) > 0 {
				reg, err := loadExtensionRegistry(rs)
				if err != nil {
					return err
				}
				repoRules = extensionRows(rs, reg)
			}
			block := buildAgentsBlock(rs, repoRules)
			if !write {
				fmt.Fprint(cmd.OutOrStdout(), block)
				return nil
			}
			target := filepath.Join(rs.Root, "AGENTS.md")
			changed, err := installAgentsBlock(target, block)
			if err != nil {
				return &exitError{2, err.Error()}
			}
			if changed {
				fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", target)
			} else {
				fmt.Fprintf(cmd.OutOrStdout(), "%s already current\n", target)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&rulesFlag, "rules", "", "path to rules.yaml (default: discovered upward from .)")
	cmd.Flags().BoolVar(&write, "write", false, "install or refresh the block in <repo-root>/AGENTS.md")
	return cmd
}

// buildAgentsBlock renders the generated block, markers included. The
// output is deterministic for one ruleset: no timestamps, sorted module
// order (rs.Instances and moduleContext follow declaration/name order).
func buildAgentsBlock(rs *config.RuleSet, repoRules []config.RuleInstance) string {
	var b strings.Builder
	b.WriteString(agentsBegin + "\n")
	b.WriteString("_Generated by `arclint agents --write` from rules.yaml; edits between the markers are overwritten._\n\n")
	b.WriteString("## Architecture contracts (arclint)\n\n")
	fmt.Fprintf(&b, "Enforced from rules.yaml: %d rules over targets [%s]. Before editing under\n",
		len(rs.Instances())+len(repoRules), strings.Join(rs.Runtime, ", "))
	b.WriteString("a path, run `arclint context <path>` for the modules, allowed imports, and\n")
	b.WriteString("rules that bind it. Verify changes with `arclint check .`.\n\n")

	b.WriteString("### Modules\n\n")
	names := make([]string, 0, len(rs.Modules))
	for name := range rs.Modules {
		names = append(names, name)
	}
	// moduleContext reads per-name; render in sorted order.
	sort.Strings(names)
	for _, name := range names {
		m := moduleContext(rs, name)
		line := "- **" + m.Name + "**"
		if m.Description != "" {
			line += " — " + m.Description
		}
		details := []string{"paths " + strings.Join(m.Paths, " ")}
		if m.Internal != "unrestricted (no consumes contract)" {
			details = append(details, "internal imports "+m.Internal)
		}
		if m.External != "allow" {
			details = append(details, "external "+m.External)
		}
		if m.Stdlib != "allow" {
			details = append(details, "stdlib "+m.Stdlib)
		}
		b.WriteString(line + " (" + strings.Join(details, "; ") + ")\n")
	}

	if len(repoRules) > 0 {
		b.WriteString("\n### Repo-wide extension rules\n\n")
		for _, inst := range repoRules {
			b.WriteString("- **" + inst.ID + "**")
			if inst.Description != "" {
				b.WriteString(" — " + inst.Description)
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("\n### Query commands\n\n")
	b.WriteString("- `arclint context <path|module>` — architectural context of a location (`--format json`)\n")
	b.WriteString("- `arclint explain <kind|type>` — terminal docs for any rule kind\n")
	b.WriteString("- `arclint check . --only <id|ns>` — verification scoped to one rule id or namespace\n")
	b.WriteString(agentsEnd + "\n")
	return b.String()
}

// installAgentsBlock writes the block into path. A file with both
// markers has the marked range replaced; a file without markers gets
// the block appended; a missing file is created holding only the
// block. One marker without the other is a corruption error. Reports
// whether the file changed.
func installAgentsBlock(path, block string) (bool, error) {
	existing, err := os.ReadFile(path)
	switch {
	case os.IsNotExist(err):
		return true, os.WriteFile(path, []byte(block), 0o644)
	case err != nil:
		return false, err
	}
	content := string(existing)
	begin := strings.Index(content, agentsBegin)
	end := strings.Index(content, agentsEnd)
	var next string
	switch {
	case begin >= 0 && end > begin:
		next = content[:begin] + strings.TrimSuffix(block, "\n") + content[end+len(agentsEnd):]
	case begin < 0 && end < 0:
		if !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		next = content + "\n" + block
	default:
		return false, fmt.Errorf("%s: found one arclint marker without the other; repair or delete the block", path)
	}
	if next == content {
		return false, nil
	}
	return true, os.WriteFile(path, []byte(next), 0o644)
}
