package main

// End-to-end tests for the generated AGENTS.md architecture block: the
// command surface it teaches must match the binary's registered
// commands, and the block generated for the boxoffice proving ground
// must carry every section and rule the hand-modeled spec demands.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/wixregiga/arclint/internal/application"
)

// TestAgentsCommandSurfaceMatchesCLI proves the block's command surface
// against the binary: every taught command resolves, and every
// user-facing root command is taught. init is exempt: it runs before
// a ruleset exists, and the block lives in an initialized repository.
func TestAgentsCommandSurfaceMatchesCLI(t *testing.T) {
	root := repoRoot(t)
	taught := map[string]bool{}
	for _, c := range application.AgentCommandSurface() {
		args := append(strings.Fields(c.Command), "--help")
		stdout, stderr, code := runBin(t, root, os.Environ(), args...)
		if code != 0 {
			t.Errorf("taught command %q does not resolve: exit %d\nstdout: %s\nstderr: %s",
				c.Command, code, stdout, stderr)
		}
		taught[strings.Fields(c.Command)[0]] = true
	}

	stdout, stderr, code := runBin(t, root, os.Environ(), "--help")
	if code != 0 {
		t.Fatalf("--help exit %d\nstderr: %s", code, stderr)
	}
	exempt := map[string]bool{"completion": true, "help": true, "init": true}
	inCommands := false
	for _, line := range strings.Split(stdout, "\n") {
		switch {
		case strings.HasPrefix(line, "Available Commands:"):
			inCommands = true
			continue
		case inCommands && strings.TrimSpace(line) == "":
			inCommands = false
		}
		if !inCommands {
			continue
		}
		name := strings.Fields(line)[0]
		if !exempt[name] && !taught[name] {
			t.Errorf("root command %q is missing from the agents block command surface", name)
		}
	}
}

// TestAgentsBlockForBoxoffice generates the block for the boxoffice
// proving ground and verifies it as a superset of the hand-modeled
// spec: every section heading of the hand block, the imperative
// ask-first prohibition, every module, and every non-consumes rule, with
// expectations derived from the binary's own query commands, never
// frozen fixtures.
func TestAgentsBlockForBoxoffice(t *testing.T) {
	dir := filepath.Join(repoRoot(t), "testing", "boxoffice")
	block, stderr, code := runBin(t, dir, os.Environ(), "agents", "md")
	if code != 0 {
		t.Fatalf("agents md exit %d\nstderr: %s", code, stderr)
	}

	installed, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatal(err)
	}
	hand := string(installed)
	begin := strings.Index(hand, "<!-- arclint:agents:begin -->")
	end := strings.Index(hand, "<!-- arclint:agents:end -->")
	if begin < 0 || end < begin {
		t.Fatalf("boxoffice AGENTS.md carries no marked block")
	}
	for _, line := range strings.Split(hand[begin:end], "\n") {
		if strings.HasPrefix(line, "### ") && !strings.Contains(block, line) {
			t.Errorf("generated block lacks the hand block's section %q", line)
		}
	}
	for _, want := range []string{
		"IMPORTANT: you MUST ask arclint before reading around.",
		"BEFORE opening source files",
		"do NOT learn the architecture by reading file after file",
		".arclint/extensions/boxoffice.ts",
	} {
		if !strings.Contains(block, want) {
			t.Errorf("generated block lacks %q", want)
		}
	}
	if strings.Contains(block, "_Generated by") {
		t.Errorf("generated block must carry no self-disclaimer")
	}

	stdout, stderr, code := runBin(t, dir, os.Environ(), "rules")
	if code != 0 {
		t.Fatalf("rules exit %d\nstderr: %s", code, stderr)
	}
	for _, line := range strings.Split(strings.TrimSpace(stdout), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 || strings.HasPrefix(fields[1], "[consumes/") {
			continue
		}
		id := fields[0]
		name := id[strings.LastIndex(id, "/")+1:]
		if !strings.Contains(block, name) {
			t.Errorf("generated block lacks rule %q (short name %q)", id, name)
		}
	}

	stdout, stderr, code = runBin(t, dir, os.Environ(), "context", "--format", "json")
	if code != 0 {
		t.Fatalf("context exit %d\nstderr: %s", code, stderr)
	}
	var ctx struct {
		Modules []struct{ Name string }
	}
	if err := json.Unmarshal([]byte(stdout), &ctx); err != nil {
		t.Fatalf("context json: %v\n%s", err, stdout)
	}
	if len(ctx.Modules) == 0 {
		t.Fatalf("context reports no modules")
	}
	for _, m := range ctx.Modules {
		if !strings.Contains(block, "- **"+m.Name+"**") {
			t.Errorf("generated block lacks module %q", m.Name)
		}
	}
}
