// arclint extension SDK type declarations.
// Generated by `arclint sdk init`; wire types derive from the Go host
// structs (internal/ext/types.go) via tygo. Regenerate after upgrading.
declare module "arclint" {
  // Code generated by tygo. DO NOT EDIT.
  // Code generated by tools/gensdktypes (tygo) from the sobek extension host types; DO NOT EDIT.

  //////////
  // source: types.go
  /*
  Package ext implements the TypeScript extension SDK: discovery under
  .arclint/extensions/, in-process transpilation via esbuild, execution on
  sobek (the k6 pattern), a two-phase register-then-run lifecycle, and a
  sandbox with no ambient I/O.

  The types in this file are the host/extension wire contract. The
  TypeScript declarations rule authors see are generated from these
  structs (tools/gensdktypes, via tygo), so the .d.ts can never drift from
  the host.
  */

  /**
   * FileInfo is one repository file as exposed to ctx.files().
   */
  export interface FileInfo {
    path: string;
    name: string;
    stem: string;
    ext: string;
    dir: string;
    size: number /* int */;
  }
  /**
   * ImportInfo is one classified import occurrence as exposed to
   * ctx.imports(path), for every active language target.
   */
  export interface ImportInfo {
    path: string;
    line: number /* int */;
    /**
     * Class is stdlib | internal | external | unknown | cgo.
     */
    class: string;
    /**
     * TargetDir is the repo-relative package directory for internal
     * imports resolved into the tree, else "".
     */
    targetDir: string;
    /**
     * TargetFile is the repo-relative file an internal import resolves to
     * for file-granular languages (JS/TS, Python), else "".
     */
    targetFile: string;
  }
  /**
   * ParamInfo is one function or method parameter at the syntactic tier.
   */
  export interface ParamInfo {
    /**
     * Name is the parameter identifier; "" for unnamed parameters.
     */
    name?: string;
    /**
     * Type is the source-text type annotation, never resolved.
     */
    type?: string;
    /**
     * Optional marks a marker or default the language expresses.
     */
    optional?: boolean;
    /**
     * Variadic marks rest or splat parameters.
     */
    variadic?: boolean;
  }
  /**
   * DeclInfo is one declaration as exposed through ctx.facts(path).
   */
  export interface DeclInfo {
    /**
     * Kind is a small cross-language vocabulary: struct, interface,
     * type, class, enum, func, method, field, const, var.
     */
    kind: string;
    name: string;
    /**
     * Owner names the enclosing declaration for members (receiver
     * type, interface, class), else "".
     */
    owner: string;
    /**
     * Exported follows the language's own visibility convention.
     */
    exported: boolean;
    startLine: number /* int */;
    endLine: number /* int */;
    /**
     * Params and Results carry the syntactic signature of func and
     * method decls; absent for every other kind.
     */
    params?: ParamInfo[];
    results?: string[];
  }
  /**
   * FactsInfo is the declaration-fact view of one file as exposed to
   * ctx.facts(path). Only languages that honestly supply declarations
   * produce one; today that is Go (parser-exact).
   */
  export interface FactsInfo {
    path: string;
    /**
     * Package is the Go package clause; "" for other languages.
     */
    package: string;
    decls: DeclInfo[];
    parseError?: string;
  }
  /**
   * ViolationInput is what ctx.report() accepts from a rule. Severity
   * is not part of the wire shape: in the target model it belongs to
   * the Rule, never to one finding.
   */
  export interface ViolationInput {
    path: string;
    message: string;
    line?: number /* int */;
    fixHint?: string;
  }


  export type Capability = "exact" | "structural" | "heuristic" | "advisory";

  export interface Ctx {
    /** Repository files, optionally filtered by a doublestar glob. */
    files(glob?: string): FileInfo[];
    /** Read one file's content. Throws on unreadable paths. */
    read(path: string): string;
    /** Classified imports of one file, for every active language target. */
    imports(path: string): ImportInfo[];
    /** Declared module names to their member file paths. */
    modules(): Record<string, string[]>;
    /** Declaration facts for one file; null when the file's language
     * does not supply declarations (today: Go only, parser-exact). */
    facts(path: string): FactsInfo | null;
    /** The sorted module names a file belongs to. */
    moduleOf(path: string): string[];
    /** Report one violation. */
    report(v: ViolationInput): void;
  }

  export interface Schema {
    optional(): Schema;
    default(v: unknown): Schema;
    describe(d: string): Schema;
    toJSON(): Record<string, unknown>;
  }

  /** Minimal zod-style schema builder producing JSON Schema; the host
   * validates rules.yaml params against it before check() runs. */
  export const s: {
    string(): Schema;
    number(): Schema;
    integer(): Schema;
    boolean(): Schema;
    enum(...values: string[]): Schema;
    array(items: Schema): Schema;
    object(props: Record<string, Schema>): Schema;
  };

  export interface RuleDef {
    /** Unique rule type name, referenced by rules.yaml entries. */
    type: string;
    /** One-line summary shown by arclint explain / rules ls. */
    description?: string;
    /** How this rule enforces its claim: exact (imports/syntax facts),
     * structural (paths/declarations), heuristic (names/regex/complexity),
     * advisory (guidance only). Default: heuristic, the conservative claim. */
    capability?: Capability;
    /** Params schema; YAML params are host-validated against it. */
    params?: Schema;
    check(ctx: Ctx, params: Record<string, unknown>): void;
  }

  export function defineRule(def: RuleDef): unknown;

}
