package application

import (
	"fmt"
	"strings"
)

// AgentsPublisher installs the generated architecture block into the
// repository's agent documentation, preserving everything outside the
// managed markers. It reports whether the document changed.
type AgentsPublisher interface {
	Install(block string) (changed bool, path string, err error)
}

// AgentsMarkers delimit the generated block; hand-written content
// outside them survives every regeneration.
const (
	AgentsBegin = "<!-- arclint:agents:begin -->"
	AgentsEnd   = "<!-- arclint:agents:end -->"
)

// PublishAgentsContext compiles the ruleset into the compact
// architecture block a coding agent needs at prompt time, and installs
// it through the publisher port. The rendered block is the business
// artifact: deterministic for one ruleset, no timestamps.
type PublishAgentsContext struct {
	context   GetArchitecturalContext
	publisher AgentsPublisher
}

// NewPublishAgentsContext requires the context use case and the
// publisher port.
func NewPublishAgentsContext(context GetArchitecturalContext, publisher AgentsPublisher) (PublishAgentsContext, error) {
	if context == (GetArchitecturalContext{}) {
		return PublishAgentsContext{}, fmt.Errorf("publish agents context: missing context use case")
	}
	if publisher == nil {
		return PublishAgentsContext{}, fmt.Errorf("publish agents context: missing publisher")
	}
	return PublishAgentsContext{context: context, publisher: publisher}, nil
}

// Render compiles the block without installing it.
func (uc PublishAgentsContext) Render() (string, error) {
	ctx, err := uc.context.Execute(ContextRequest{})
	if err != nil {
		return "", err
	}
	return renderAgentsBlock(ctx), nil
}

// Execute compiles and installs the block, reporting whether the
// document changed and where it lives.
func (uc PublishAgentsContext) Execute() (changed bool, path string, err error) {
	block, err := uc.Render()
	if err != nil {
		return false, "", err
	}
	changed, path, err = uc.publisher.Install(block)
	if err != nil {
		return false, "", fmt.Errorf("install agents context: %w", err)
	}
	return changed, path, nil
}

func renderAgentsBlock(ctx ArchitecturalContext) string {
	var b strings.Builder
	b.WriteString(AgentsBegin + "\n")
	b.WriteString("_Generated by `arclint agents md --write` from rules.yaml; edits between the markers are overwritten._\n\n")
	b.WriteString("## Architecture contracts (arclint)\n\n")
	fmt.Fprintf(&b, "Enforced from rules.yaml: %d rules over languages [%s]. Before editing under\n",
		ctx.RuleCount, strings.Join(ctx.Languages, ", "))
	b.WriteString("a path, run `arclint context <paths...>` for the modules and rules that bind it.\n")
	b.WriteString("Verify changes with `arclint check .`.\n\n")

	b.WriteString("### Modules\n\n")
	for _, m := range ctx.Modules {
		line := "- **" + m.Name + "**"
		if m.Description != "" {
			line += " — " + m.Description
		}
		details := []string{"paths " + strings.Join(m.Paths, " ")}
		if m.InternalRestricted {
			policy := "allow: " + strings.Join(m.Internal, ", ")
			if len(m.Internal) == 0 {
				policy = "none (may import no other declared module)"
			}
			details = append(details, "internal imports "+policy)
		}
		if m.External != "allow" {
			details = append(details, "external "+m.External)
		}
		if m.Stdlib != "allow" {
			details = append(details, "stdlib "+m.Stdlib)
		}
		b.WriteString(line + " (" + strings.Join(details, "; ") + ")\n")
	}

	b.WriteString("\n### Query commands\n\n")
	b.WriteString("- `arclint context [paths...]` — the architecture, or everything binding the given paths (`--module <names>`, `--format json`)\n")
	b.WriteString("- `arclint rules [selector]` — the configured rules; one match shows the complete Rule\n")
	b.WriteString("- `arclint check .` — evaluate every rule; exit 1 on error-severity findings\n")
	b.WriteString(AgentsEnd + "\n")
	return b.String()
}
