// arclint extension SDK type declarations.
// Generated by `arclint sdk init`; wire types derive from the Go host
// structs (internal/ext/types.go) via tygo. Regenerate after upgrading.
declare module "arclint" {
  // Code generated by tygo. DO NOT EDIT.
  // Code generated by tools/gensdktypes (tygo) from the sobek extension host types; DO NOT EDIT.

  //////////
  // source: types.go
  /*
  Package sobekextension implements the TypeScript extension SDK:
  discovery under .arclint/extensions/, in-process transpilation via
  esbuild, execution on sobek (the k6 pattern), a two-phase
  register-then-run lifecycle, and a sandbox with no ambient I/O.

  The types in this file are the host/extension wire contract. The
  TypeScript declarations rule authors see are generated from these
  structs (tools/gensdktypes, via tygo), so the .d.ts can never drift from
  the host.
  */

  /**
   * FileInfo is one repository file as exposed to ctx.files().
   */
  export interface FileInfo {
    path: string;
    name: string;
    stem: string;
    ext: string;
    dir: string;
    size: number /* int */;
  }
  /**
   * ImportInfo is one classified import occurrence as exposed to
   * ctx.imports(path), for every active language target.
   */
  export interface ImportInfo {
    path: string;
    line: number /* int */;
    /**
     * Class is stdlib | internal | external | unknown | cgo.
     */
    class: string;
    /**
     * TargetDir is the repo-relative package directory for internal
     * imports resolved into the tree, else "".
     */
    targetDir: string;
    /**
     * TargetFile is the repo-relative file an internal import resolves to
     * for file-granular languages (JS/TS, Python), else "".
     */
    targetFile: string;
  }
  /**
   * ParamInfo is one function or method parameter at the syntactic tier.
   */
  export interface ParamInfo {
    /**
     * Name is the parameter identifier; "" for unnamed parameters.
     */
    name?: string;
    /**
     * Type is the source-text type annotation, never resolved.
     */
    type?: string;
    /**
     * Optional marks a marker or default the language expresses.
     */
    optional?: boolean;
    /**
     * Variadic marks rest or splat parameters.
     */
    variadic?: boolean;
  }
  /**
   * DeclInfo is one declaration as exposed through ctx.facts(path).
   */
  export interface DeclInfo {
    /**
     * Kind is a small cross-language vocabulary: struct, interface,
     * type, class, enum, func, method, field, const, var.
     */
    kind: string;
    name: string;
    /**
     * Owner names the enclosing declaration for members (receiver
     * type, interface, class), else "".
     */
    owner: string;
    /**
     * Exported follows the language's own visibility convention.
     */
    exported: boolean;
    startLine: number /* int */;
    endLine: number /* int */;
    /**
     * Params and Results carry the syntactic signature of func and
     * method decls; absent for every other kind.
     */
    params?: ParamInfo[];
    results?: string[];
  }
  /**
   * FactsInfo is the cross-language declaration-fact view of one file as
   * exposed through ctx.facts(path). Languages return only declarations
   * they can support honestly.
   */
  export interface FactsInfo {
    path: string;
    /**
     * Package is the Go package clause; "" for other languages.
     */
    package: string;
    decls: DeclInfo[];
    parseError?: string;
  }
  /**
   * ViolationInput is what ctx.report() accepts from a rule. Severity
   * is not part of the wire shape: in the target model it belongs to
   * the Rule, never to one finding.
   */
  export interface ViolationInput {
    path: string;
    message: string;
    line?: number /* int */;
    fixHint?: string;
  }
  /**
   * DomainDefinitionInfo is one recorded project domain definition as
   * exposed through ctx.domain(). Line is where the term is written in
   * domain.arclint.yaml, so a finding about the term can anchor at
   * the term; 0 when the vocabulary was not read from a file.
   */
  export interface DomainDefinitionInfo {
    name: string;
    definition?: string;
    aliases?: string[];
    aggregate?: boolean;
    line: number /* int */;
  }
  /**
   * DomainInvariantInfo is one recorded invariant (statement + owner)
   * inside a bounded context as exposed through ctx.domain(). Line is
   * where the invariant is written in domain.arclint.yaml. ID is
   * the cluster identity when the owner is an aggregate named contract.
   */
  export interface DomainInvariantInfo {
    statement: string;
    owner: string;
    id?: string;
    line: number /* int */;
  }
  /**
   * DomainAssertionInfo is one recorded assertion as exposed through
   * ctx.domain(). ID names the checking method; On names the operation
   * that must call it.
   */
  export interface DomainAssertionInfo {
    statement: string;
    owner: string;
    id: string;
    on: string;
    line: number /* int */;
  }
  /**
   * DomainSpecificationInfo is one recorded specification as exposed
   * through ctx.domain(): a named predicate, never a flag on a value
   * object.
   */
  export interface DomainSpecificationInfo {
    name: string;
    definition?: string;
    line: number /* int */;
  }
  /**
   * DomainContextInfo is one bounded context and its recorded terms as
   * exposed through ctx.domain(). Line is where the context is written
   * in domain.arclint.yaml.
   */
  export interface DomainContextInfo {
    name: string;
    entities: DomainDefinitionInfo[];
    valueObjects: DomainDefinitionInfo[];
    invariants: DomainInvariantInfo[];
    assertions: DomainAssertionInfo[];
    specifications: DomainSpecificationInfo[];
    events: DomainDefinitionInfo[];
    line: number /* int */;
  }
  /**
   * DomainRelationInfo is one context-map edge as exposed through
   * ctx.domain(). Line is where the relation is written in
   * domain.arclint.yaml.
   */
  export interface DomainRelationInfo {
    from: string;
    to: string;
    kind: string;
    line: number /* int */;
  }
  /**
   * DomainInfo is the project's recorded domain model as exposed through
   * ctx.domain(): empty collections when the project records none.
   * Read-only: declaring knowledge never creates a diagnostic by itself.
   * Source is the repository-relative path of the domain file the model
   * is (or would be) recorded in, so a finding about a recorded term
   * anchors there without the extension spelling the file name.
   */
  export interface DomainInfo {
    source: string;
    contexts: DomainContextInfo[];
    relations: DomainRelationInfo[];
  }


  export type Capability = "exact" | "structural" | "heuristic" | "advisory";

  /** Published TermCases: renderings of a recorded vocabulary term as a
   * path or identifier segment. The same closed set rules.arclint.yaml accepts in
   * {name:<case>} placeholders. */
  export type TermCase =
    | "flatcase"
    | "snake_case"
    | "kebab-case"
    | "camelCase"
    | "PascalCase";

  export interface Ctx {
    /** Repository files, optionally filtered by a doublestar glob. */
    files(glob?: string): FileInfo[];
    /** Read one file's content. Throws on unreadable paths. */
    read(path: string): string;
    /** Classified imports of one file, for every active language target. */
    imports(path: string): ImportInfo[];
    /** Declared module names to their member file paths. */
    modules(): Record<string, string[]>;
    /** Cross-language declaration facts for one file; null when its
     * language did not supply declarations. */
    facts(path: string): FactsInfo | null;
    /** The sorted module names a file belongs to. */
    moduleOf(path: string): string[];
    /** The project's recorded domain model (domain.arclint.yaml);
     * empty collections when the project records none. Read-only:
     * declaring knowledge never creates a diagnostic by itself. */
    domain(): DomainInfo;
    /** Render a recorded term in one published TermCase, the host's
     * one casing implementation, identical to what rules.arclint.yaml
     * {name:<case>} placeholders resolve with. Throws on an unknown
     * case and on terms without letters or digits. */
    caseTerm(term: string, termCase: TermCase): string;
    /** Report one violation. */
    report(v: ViolationInput): void;
  }

  export interface Schema {
    optional(): Schema;
    default(v: unknown): Schema;
    describe(d: string): Schema;
    toJSON(): Record<string, unknown>;
  }

  /** Minimal zod-style schema builder producing JSON Schema; the host
   * validates rules.arclint.yaml params against it before check() runs. */
  export const s: {
    string(): Schema;
    number(): Schema;
    integer(): Schema;
    boolean(): Schema;
    enum(...values: string[]): Schema;
    array(items: Schema): Schema;
    object(props: Record<string, Schema>): Schema;
  };

  export interface RuleDef {
    /** Unique rule type name, referenced by rules.arclint.yaml entries. */
    type: string;
    /** One-line summary shown by arclint rules. */
    description?: string;
    /** How this rule enforces its claim: exact (imports/syntax facts),
     * structural (paths/declarations), heuristic (names/regex/complexity),
     * advisory (guidance only). Default: heuristic, the conservative claim. */
    capability?: Capability;
    /** Params schema; YAML params are host-validated against it. */
    params?: Schema;
    check(ctx: Ctx, params: Record<string, unknown>): void;
  }

  export function defineRule(def: RuleDef): unknown;

}
