// Command genstdlib generates the embedded Go standard-library package
// table from `go list std` of the toolchain running go:generate. Exact
// classification, no heuristics: the table is the single source of truth
// for stdlib membership.
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"runtime"
	"sort"
	"strings"
)

func main() {
	out := flag.String("out", "stdlib_gen.go", "output file")
	pkg := flag.String("pkg", "golang", "package name")
	flag.Parse()

	cmd := exec.CommandContext(context.Background(), "go", "list", "std")
	cmd.Stderr = os.Stderr
	raw, err := cmd.Output()
	if err != nil {
		log.Fatalf("go list std: %v", err)
	}
	var pkgs []string
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// `go list std` can surface the std module's vendored copies as
		// vendor/golang.org/...; those paths are not importable by user
		// code and are excluded from the table.
		if strings.HasPrefix(line, "vendor/") {
			continue
		}
		pkgs = append(pkgs, line)
	}
	if len(pkgs) < 100 {
		log.Fatalf("go list std returned %d packages; expected the full standard library", len(pkgs))
	}
	sort.Strings(pkgs)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/genstdlib; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: `go list std` of %s.\n\n", runtime.Version())
	fmt.Fprintf(&b, "package %s\n\n", *pkg)
	fmt.Fprintf(&b, "// StdlibToolchain is the toolchain whose `go list std` produced the table.\n")
	fmt.Fprintf(&b, "const StdlibToolchain = %q\n\n", runtime.Version())
	fmt.Fprintf(&b, "var stdlibPackages = map[string]struct{}{\n")
	for _, p := range pkgs {
		fmt.Fprintf(&b, "\t%q: {},\n", p)
	}
	fmt.Fprintf(&b, "}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("generated source does not format: %v", err)
	}
	if err := os.WriteFile(*out, formatted, 0o600); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s: %d packages (%s)\n", *out, len(pkgs), runtime.Version())
}
