package main

import (
	"fmt"
	"io/fs"
	"regexp"
	"strings"

	"github.com/wixregiga/arclint/internal/domain/rule"
	"github.com/wixregiga/arclint/internal/domain/vocab"
	vocabyaml "github.com/wixregiga/arclint/internal/infrastructure/vocab/yaml"
)

// The two families the page teaches, in the order it teaches them. A
// rule family block says where a rule of the business lives; a behavior
// family block says which operation carries it.
var (
	ruleFamily     = []string{"invariant", "assertion", "specification"}
	behaviorFamily = []string{"command", "query", "domain_service", "application_service", "domain_event"}
)

// The example the page walks through, and the recorded entries its
// rule-homes table quotes from the example's domain file.
const (
	goExample        = "docs/examples/go"
	tsExample        = "docs/examples/ts"
	exampleDomain    = goExample + "/domain.arclint.yaml"
	exampleContext   = "identityaccess"
	exampleValue     = "TenantName"
	exampleAggregate = "Tenant"
	exampleService   = "TenantProvisioningService"
	exampleServiceAs = "tenant-active-on-completion"
)

// render builds the page from the meta-model, the librarian's questions,
// and the examples read from repo.
func render(repo fs.FS) ([]byte, error) {
	sn, err := readSnippets(repo)
	if err != nil {
		return nil, err
	}
	data, err := fs.ReadFile(repo, exampleDomain)
	if err != nil {
		return nil, fmt.Errorf("read the Go example's domain file: %w", err)
	}
	tsData, err := fs.ReadFile(repo, tsExample+"/domain.arclint.yaml")
	if err != nil {
		return nil, fmt.Errorf("read the TypeScript example's domain file: %w", err)
	}
	if string(data) != string(tsData) {
		return nil, fmt.Errorf("domain.arclint.yaml differs between %s and %s; the two examples record one domain", goExample, tsExample)
	}
	lang, err := vocabyaml.Parse(data)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", exampleDomain, err)
	}
	ctx, ok := lang.Context(exampleContext)
	if !ok {
		return nil, fmt.Errorf("%s records no context %q", exampleDomain, exampleContext)
	}

	p := &page{m: vocab.DDD(), sn: sn, index: map[string]int{}}
	p.front()
	if err := p.intake(); err != nil {
		return nil, err
	}
	if err := p.family("Rules: where a rule lives", "A rule the model has placed is one of three things. Each is recorded under the owner that keeps it true, and each names the method that checks it.", ruleFamily); err != nil {
		return nil, err
	}
	if err := p.family("Behavior: which operation carries it", "A rule is checked by an operation. These are the operations a model and the application around it are built from, and the one record of what they did.", behaviorFamily); err != nil {
		return nil, err
	}
	if err := p.homes(ctx); err != nil {
		return nil, err
	}
	if err := p.walkThrough(); err != nil {
		return nil, err
	}
	p.questions()
	p.references()
	if unused := sn.unused(); len(unused) > 0 {
		return nil, fmt.Errorf("anchors the page never quotes: %s", strings.Join(unused, ", "))
	}
	return []byte(p.b.String()), nil
}

// page accumulates the Markdown and the numbered list of references the
// text cites, numbered in the order of first citation.
type page struct {
	b     strings.Builder
	m     vocab.MetaModel
	sn    *snippets
	refs  []string
	index map[string]int
}

func (p *page) printf(format string, args ...any) { fmt.Fprintf(&p.b, format, args...) }

// cite resolves citations against the meta-model's works and returns
// their numbered links, each work cited once per call.
func (p *page) cite(cs []vocab.Citation) string {
	var links []string
	seen := map[int]bool{}
	for _, r := range p.m.References(cs) {
		s := r.String()
		n, ok := p.index[s]
		if !ok {
			p.refs = append(p.refs, s)
			n = len(p.refs)
			p.index[s] = n
		}
		if !seen[n] {
			seen[n] = true
			links = append(links, fmt.Sprintf("[[%d]](#ref-%d)", n, n))
		}
	}
	if len(links) == 0 {
		return ""
	}
	return " " + strings.Join(links, "")
}

func (p *page) block(term string) (vocab.BuildingBlock, error) {
	b, ok := p.m.Block(term)
	if !ok {
		return vocab.BuildingBlock{}, fmt.Errorf("the meta-model has no building block %q", term)
	}
	return b, nil
}

func (p *page) front() {
	p.printf("+++\n")
	p.printf("title = \"Classifying\"\n")
	p.printf("description = \"Where a rule of the business lives, which operation checks it, and the questions that decide when the input does not say.\"\n")
	p.printf("weight = 8\n")
	p.printf("+++\n\n")
	p.printf("<!-- Code generated by tools/genclassifying from the meta-model in internal/domain/vocab and the examples under docs/examples; DO NOT EDIT. -->\n\n")
	p.printf("A domain expert states a rule; the model has to put it somewhere. This page is the vocabulary arclint and the domain-librarian skill use to place it: ")
	p.printf("the definitions, recordings, and checks come from the Domain-Driven Design meta-model arclint carries (`arclint domain`), ")
	p.printf("the questions are the ones the skill asks, and every code sample is quoted from a worked example under `docs/examples`: the Go example compiles and passes its tests, and both examples pass `arclint check`. ")
	p.printf("A rule id such as `invariant/enforced-at-every-mutation` is a built-in rule; `arclint rules <id>` prints it in full.\n\n")
}

// intake explains business rule, the word a rule arrives under before
// it is placed.
func (p *page) intake() error {
	b, err := p.block("business_rule")
	if err != nil {
		return err
	}
	p.printf("## %s is an intake word\n\n", sentenceCase(b.Title))
	p.printf("%s%s\n\n", b.Definition.Text, p.cite(b.Definition.Sources))
	p.printf("%s\n\n", b.Records.Note)
	p.guidance(b.Guidance)
	return nil
}

// family writes one section per building block of a family.
func (p *page) family(title, lead string, terms []string) error {
	p.printf("## %s\n\n%s\n\n", title, lead)
	for _, term := range terms {
		b, err := p.block(term)
		if err != nil {
			return err
		}
		p.printf("### %s\n\n", b.Title)
		p.printf("%s%s\n\n", b.Definition.Text, p.cite(b.Definition.Sources))
		if b.Records.Section == vocab.SectionNone {
			p.printf("**Recording:** %s\n\n", b.Records.Note)
		} else {
			p.printf("**Recorded under** `%s`.", b.Records.Section)
			if b.Records.Note != "" {
				p.printf(" %s", b.Records.Note)
			}
			p.printf("\n\n")
		}
		if len(b.Records.Properties) > 0 {
			p.printf("| Property | Required | Meaning |\n|---|---|---|\n")
			for _, prop := range b.Records.Properties {
				p.printf("| `%s` | %s | %s |\n", prop.Name, yesNo(prop.Required), cell(prop.Definition))
			}
			p.printf("\n")
		}
		if len(b.Invariants) > 0 {
			p.printf("| Rule | What holds | Checked |\n|---|---|---|\n")
			for _, inv := range b.Invariants {
				p.printf("| `%s` | %s%s | %s |\n", inv.ID, cell(inv.Statement), p.cite(inv.Sources), checked(inv))
			}
			p.printf("\n")
		}
		p.guidance(b.Guidance)
	}
	return nil
}

func (p *page) guidance(gs []vocab.Guidance) {
	if len(gs) == 0 {
		return
	}
	for _, g := range gs {
		mark := ""
		if g.Fundamental {
			mark = "**Fundamental.** "
		}
		p.printf("- %s%s%s\n", mark, g.Text, p.cite(g.Sources))
	}
	p.printf("\n")
}

// checked says where a block invariant is evaluated.
func checked(inv vocab.BlockInvariant) string {
	var s string
	switch inv.Level() {
	case vocab.LevelRecording:
		s = "when the domain file loads"
	case vocab.LevelCheck:
		s = "by `arclint check`"
		if !inv.Enforcement.Languages.All {
			s += " in " + strings.Join(inv.Enforcement.Languages.Names, ", ")
		}
	case vocab.LevelMilestone:
		s = "not yet; waits for the `" + inv.Enforcement.Needs + "` milestone"
	}
	if inv.Enforcement.Severity == "warning" {
		s += ", as a warning"
	}
	return s
}

// homes writes the table of where each kind of rule lives, quoting the
// example's recorded entries and the method names they spell.
func (p *page) homes(ctx vocab.BoundedContext) error {
	value, ok := ctx.ValueObject(exampleValue)
	if !ok || len(value.Invariants) == 0 {
		return fmt.Errorf("%s records no value object %s with an invariant", exampleDomain, exampleValue)
	}
	agg, ok := ctx.Aggregate(exampleAggregate)
	if !ok || len(agg.Invariants) == 0 || len(agg.Assertions) == 0 {
		return fmt.Errorf("%s records no aggregate %s with an invariant and an assertion", exampleDomain, exampleAggregate)
	}
	svc, ok := ctx.Service(exampleService)
	if !ok {
		return fmt.Errorf("%s records no service %s", exampleDomain, exampleService)
	}
	svcAs, ok := svc.Assertion(exampleServiceAs)
	if !ok {
		return fmt.Errorf("%s: service %s records no assertion %s", exampleDomain, exampleService, exampleServiceAs)
	}
	valueInv, aggInv, aggAs := value.Invariants[0], agg.Invariants[0], agg.Assertions[0]

	door, err := p.declared("value-door")
	if err != nil {
		return err
	}
	flow, err := p.declared("application-service")
	if err != nil {
		return err
	}
	ensure, err := p.spelled("ensure", "ensure-"+aggInv.Key)
	if err != nil {
		return err
	}
	assert, err := p.spelled("assert", "assert-"+aggAs.Key)
	if err != nil {
		return err
	}
	svcAssert, err := p.spelled("service-assert", "assert-"+svcAs.Key)
	if err != nil {
		return err
	}

	type row struct {
		rule, recorded, lives, check, example, goCell, tsCell string
		rules                                                 []string
	}
	rows := []row{
		{
			"invariant of a value", "`invariants` under the value object", "value object", "its constructor, the one door",
			fmt.Sprintf("`%s`: `%s`", value.Name, valueInv.Key), door[0], door[1],
			[]string{"value_object/constructed-through-one-door"},
		},
		{
			"invariant of a cluster", "`invariants` under the aggregate", "aggregate root", "`Ensure` and the key, called by every constructor and command",
			fmt.Sprintf("`%s`: `%s`", agg.Name, aggInv.Key), ensure[0], ensure[1],
			[]string{"aggregate/invariants-enforced-by-root", "invariant/enforced-at-every-mutation"},
		},
		{
			"assertion on a command", "`assertions` under the aggregate, `on` the command", "aggregate root", "`Assert` and the key, called by that command",
			fmt.Sprintf("`%s`: `%s` on `%s`", agg.Name, aggAs.Key, aggAs.On), assert[0], assert[1],
			[]string{"assertion/checked-by-its-operation"},
		},
		{
			"assertion on a service operation", "`assertions` under the domain service, `on` the operation", "domain service", "`Assert` and the key, called by that operation",
			fmt.Sprintf("`%s`: `%s` on `%s`", svc.Name, svcAs.Key, svcAs.On), svcAssert[0], svcAssert[1],
			[]string{"assertion/checked-by-its-operation"},
		},
		{
			"specification", "`specifications`", "its own type", "`SatisfiedBy`",
			"the example records none", "", "",
			[]string{"specification/satisfaction-method"},
		},
		{
			"delivery policy: notify, export, retry, commit", "not recorded", "application service, or a subscriber to a domain event", "plain code",
			"publishing the events after the unit of work", flow[0], flow[1], nil,
		},
		{
			"programming guard: a nil check, a parse failure", "not recorded", "the code that needs it", "plain code",
			"", "", "", nil,
		},
	}
	p.printf("## Where each rule lives\n\n")
	p.printf("The example column quotes the worked example's `domain.arclint.yaml`; the Go and TypeScript columns name the method each language spells for it, read from the example's code.\n\n")
	p.printf("| The rule is | Recorded as | Lives on | Checked by | In the example | Go | TypeScript | Built-in rules |\n")
	p.printf("|---|---|---|---|---|---|---|---|\n")
	for _, r := range rows {
		var ids []string
		for _, id := range r.rules {
			inv, ok := p.m.Invariant(id)
			if !ok {
				return fmt.Errorf("the meta-model has no invariant %q", id)
			}
			if inv.Level() != vocab.LevelCheck {
				return fmt.Errorf("%s is not evaluated by arclint check; the table lists only rules that are", id)
			}
			ids = append(ids, "`"+id+"`")
		}
		p.printf("| %s | %s | %s | %s | %s | %s | %s | %s |\n",
			r.rule, r.recorded, r.lives, r.check, r.example, code(r.goCell), code(r.tsCell), strings.Join(ids, "<br>"))
	}
	p.printf("\n")
	ab, err := p.block("application_service")
	if err != nil {
		return err
	}
	for _, g := range ab.Guidance {
		if g.Fundamental {
			p.printf("The application service is the one place a rule never lives: %s%s\n\n", lowerFirst(g.Text), p.cite(g.Sources))
		}
	}
	return nil
}

// declared reads the name the Go and TypeScript snippets of an anchor
// declare first: a Go function or method, a TypeScript method, a static
// factory spelled Type.method.
func (p *page) declared(anchor string) ([2]string, error) {
	var out [2]string
	g, err := p.sn.get(goExample, anchor)
	if err != nil {
		return out, err
	}
	t, err := p.sn.get(tsExample, anchor)
	if err != nil {
		return out, err
	}
	gm := goDecl.FindStringSubmatch(g.text)
	tm := tsDecl.FindStringSubmatch(t.text)
	if gm == nil || tm == nil {
		return out, fmt.Errorf("anchor %q: no declaration in the Go or the TypeScript snippet", anchor)
	}
	out[0] = gm[1]
	out[1] = tm[2]
	if tm[1] != "" {
		// A static factory is spelled with the class it is a door of,
		// the type it returns.
		ret := tsStaticReturn.FindStringSubmatch(t.text)
		if ret == nil {
			return out, fmt.Errorf("anchor %q: the TypeScript factory %s declares no return type", anchor, tm[2])
		}
		out[1] = ret[1] + "." + tm[2]
	}
	return out, nil
}

var (
	goDecl         = regexp.MustCompile(`(?m)^func (?:\([^)]*\) )?(\w+)\(`)
	tsDecl         = regexp.MustCompile(`(?m)^(static )?(?:async )?([a-zA-Z]\w*)\(`)
	tsStaticReturn = regexp.MustCompile(`(?m)^static \w+\([^)]*\): (\w+)`)
)

// spelled returns the Go and TypeScript spellings of a method named for
// a key, and requires both snippets of the anchor to declare them.
func (p *page) spelled(anchor, term string) ([2]string, error) {
	names, err := spellings(term)
	if err != nil {
		return names, err
	}
	g, err := p.sn.get(goExample, anchor)
	if err != nil {
		return names, err
	}
	t, err := p.sn.get(tsExample, anchor)
	if err != nil {
		return names, err
	}
	if !strings.Contains(g.text, ") "+names[0]+"(") || !strings.Contains(t.text, names[1]+"(") {
		return names, fmt.Errorf("anchor %q does not declare %s in Go and %s in TypeScript", anchor, names[0], names[1])
	}
	return names, nil
}

// spellings renders a term in the method case of Go and of TypeScript.
func spellings(term string) ([2]string, error) {
	var out [2]string
	var err error
	if out[0], err = rule.CaseTerm(term, "PascalCase"); err != nil {
		return out, fmt.Errorf("spell %q for Go: %w", term, err)
	}
	if out[1], err = rule.CaseTerm(term, "camelCase"); err != nil {
		return out, fmt.Errorf("spell %q for TypeScript: %w", term, err)
	}
	return out, nil
}

// walkThrough quotes the example top to bottom: the use case, the
// domain service, the aggregate's commands, query, and checks, the
// value's door, the event, and the rule no one owns.
func (p *page) walkThrough() error {
	p.printf("## Provisioning a tenant, top to bottom\n\n")
	p.printf("The worked example is the identity and access context of Vernon's *Implementing Domain-Driven Design*, written twice: in Go under `docs/examples/go` and in TypeScript under `docs/examples/ts`, from one `domain.arclint.yaml`. ")
	p.printf("Provisioning a tenant touches every word above.\n\n")
	steps := []struct {
		title, text string
		anchors     []string
	}{
		{
			"The application service runs the use case",
			"`ProvisionTenant` translates the request into domain values, runs the domain service inside one unit of work, and publishes the events the aggregates raised. It makes no business decision of its own.",
			[]string{"application-service"},
		},
		{
			"The domain service makes the decision that spans aggregates",
			"Provisioning creates a Tenant, a User, and a Role together, which no one of them can do alone. The service's contract is the assertions recorded under it:",
			[]string{"yaml:service-recording", "service-operation"},
		},
		{
			"", "Each assertion is checked by a method named `assert` and the key, and the operation calls it:",
			[]string{"service-assert"},
		},
		{
			"The aggregate checks its commands",
			"The Tenant records one invariant and one assertion:",
			[]string{"yaml:tenant-recording"},
		},
		{
			"", "Offering an invitation is a command: it changes the tenant and is named for what it does. It checks the assertion first and the invariant last.",
			[]string{"command-assert", "assert"},
		},
		{
			"", "Deactivating the tenant carries no assertion, but like every command it ends by calling the invariant's ensure method:",
			[]string{"command-ensure", "ensure"},
		},
		{
			"A query answers without changing anything",
			"Whether a user may register through an invitation is a query; the command above asks it before it changes anything.",
			[]string{"query"},
		},
		{
			"A value keeps its own invariant at its one door",
			"`TenantName` records the invariant `length-within-bounds`. Its constructor is the only way to make one, so no tenant name outside the bounds exists.",
			[]string{"value-door"},
		},
		{
			"An event records what happened",
			"Provisioning raises `TenantProvisioned`. The aggregate raises it; the application service publishes it after the unit of work completes.",
			[]string{"event"},
		},
		{
			"A rule with no owner is a question",
			"No two tenants share a name, but no one tenant owns that rule, so it is not recorded as an invariant. It stays an open question for the domain expert until they answer it:",
			[]string{"yaml:question-recording"},
		},
	}
	n := 0
	for _, s := range steps {
		if s.title != "" {
			n++
			p.printf("### %d. %s\n\n", n, s.title)
		}
		p.printf("%s\n\n", s.text)
		for _, a := range s.anchors {
			if name, ok := strings.CutPrefix(a, "yaml:"); ok {
				sn, err := p.sn.get(goExample, name)
				if err != nil {
					return err
				}
				// The TypeScript example records the same domain file;
				// render checks the two are identical.
				if _, err := p.sn.get(tsExample, name); err != nil {
					return err
				}
				p.fence("yaml", "domain.arclint.yaml", sn.text)
				continue
			}
			g, err := p.sn.get(goExample, a)
			if err != nil {
				return err
			}
			t, err := p.sn.get(tsExample, a)
			if err != nil {
				return err
			}
			p.fence("go", g.file, g.text)
			p.fence("ts", t.file, t.text)
		}
	}
	return nil
}

func (p *page) fence(lang, file, text string) {
	p.printf("`%s`\n\n```%s\n%s\n```\n\n", file, lang, text)
}

// questions writes the librarian's clarification protocol and its
// distillation rules, word for word as the skill carries them.
func (p *page) questions() {
	p.printf("## The questions that decide\n\n")
	p.printf("When the input does not say where a rule lives, the domain-librarian skill asks rather than guesses. Its policy: %s\n\n", vocab.ClarificationPolicy)
	p.printf("### When the input is not enough\n\n")
	p.questionTable(vocab.InsufficientInfoQuestions())
	p.printf("### When the input conflicts with the record\n\n")
	p.questionTable(vocab.ConflictQuestions())
	p.printf("### Distillation rules\n\n")
	p.printf("The rules the skill applies to turn what an expert said into recorded terms.\n\n")
	p.printf("| Rule | States | Example |\n|---|---|---|\n")
	for _, r := range vocab.DistillationRules() {
		p.printf("| `%s` | %s | %s |\n", r.ID, cell(r.Rule), cell(r.Example))
	}
	p.printf("\n")
}

func (p *page) questionTable(qs []vocab.ClarificationQuestion) {
	p.printf("| Question | Decides | Defined by |\n|---|---|---|\n")
	for _, q := range qs {
		var grounds []string
		for _, b := range p.decided(q.Decides) {
			grounds = append(grounds, b.Title+p.cite(b.Definition.Sources))
		}
		p.printf("| %s | %s | %s |\n", cell(q.Question), cell(q.Decides), strings.Join(grounds, "<br>"))
	}
	p.printf("\n")
}

// decided lists the building blocks a question decides between: every
// alternative of Decides that is a term by itself, and every term spelled
// in snake_case anywhere in it. "entity vs value_object" names two;
// "value integrity vs cluster invariant" names none, because neither
// alternative is a term.
func (p *page) decided(decides string) []vocab.BuildingBlock {
	var out []vocab.BuildingBlock
	seen := map[string]bool{}
	add := func(term string) {
		if b, ok := p.m.Block(term); ok && !seen[term] {
			seen[term] = true
			out = append(out, b)
		}
	}
	for _, alt := range alternatives.Split(decides, -1) {
		alt = strings.TrimSpace(alt)
		add(alt)
		for _, word := range strings.Fields(alt) {
			if strings.Contains(word, "_") {
				add(word)
			}
		}
	}
	return out
}

var alternatives = regexp.MustCompile(` vs | or |\(|\)`)

// references writes the numbered works the page cited.
func (p *page) references() {
	p.printf("## References\n\n")
	for i, r := range p.refs {
		p.printf("%d. <span id=\"ref-%d\"></span>%s\n", i+1, i+1, r)
	}
}

// cell makes text safe inside a Markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.Join(strings.Fields(s), " ")
}

func code(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// sentenceCase keeps the first word of a title as written and lowers the
// rest, so a heading that continues the title reads as one sentence.
func sentenceCase(title string) string {
	first, rest, ok := strings.Cut(title, " ")
	if !ok {
		return title
	}
	return first + " " + strings.ToLower(rest)
}
